import NormalNumbers.JointLambertAGPRange
#print axioms NormalNumbers.JointLambert.exists_pointwise_exponential_distribution
#print axioms NormalNumbers.JointLambert.agpCount_eq_primeCountUpTo
#print axioms NormalNumbers.JointLambert.maxDisc_le_excisedPrimeSum
#print axioms Erdos4.FGKMT.exists_exponential_prime_distribution
