import NormalNumbers.JointLambertAGPRange
#print axioms NormalNumbers.JointLambert.exists_pointwise_exponential_distribution
#print axioms NormalNumbers.JointLambert.exists_modulus_excision_of_unique
#print axioms NormalNumbers.JointLambert.exists_uniform_modulus_excision
