/-
Copyright (c) 2026 Trevor Morris. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Trevor Morris
-/
import NormalNumbers.AdderCert

/-!
# The toy certificate (dry run of module 3, kernel tier)

Data generated by `experiments/adder_certificate_emit.py` (which re-verifies
(C1)/(C1')/(C3') in Python and refuses to emit on failure), from
`experiments/certs/adder_cert_toy.json`: the vacuous 3-channel family
(`ln 2, ln 3, ln 6` avoiding `01, 01, 10`), ambient 16 states, 7 live.
`toy_cert_ok` is proved by kernel `decide` — this settles the module-3 route
at toy scale.
-/

namespace NormalNumbers.Adder

def toyLive : List Bool :=
  [true, false, false, false, false, true, true, false,
   false, true, true, true, false, false, false, true]

def toyRho : List ℕ := [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]

def toyOmega : List ℕ := [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

def toyForced : ℕ → Option (ℕ × ℕ)
  | 0 => some (0, 0)
  | 5 => some (1, 5)
  | 6 => some (2, 6)
  | 9 => some (1, 9)
  | 10 => some (2, 10)
  | 15 => some (3, 15)
  | _ => none

/-- The toy certificate passes the full kernel check. -/
theorem toy_cert_ok :
    checkCert toyFamily 16 (fun s => toyLive.getD s false)
      (fun s => toyRho.getD s 0) (fun s => toyOmega.getD s 0) toyForced = true := by
  decide

end NormalNumbers.Adder
