/-
Copyright (c) 2026 Trevor Morris. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Trevor Morris
-/
import NormalNumbers.Disjunctive
import Mathlib.Dynamics.Ergodic.AddCircle
import Mathlib.Dynamics.OmegaLimit
import Mathlib.Topology.Perfect

/-!
# Circle ω-limits and the conditional disjunctivity ladder (Track D, D0.5–D1)

The real-valued orbit in `Disjunctive.lean` uses canonical representatives in
`[0,1)`.  Its closure in `ℝ` includes both endpoints, so the correct compact
phase space for ω-limits is the endpoint-identified unit circle
`UnitAddCircle = ℝ ⧸ ℤ`.

This file supplies that endpoint-safe API and proves the 0–1 law needed by
Axiom Λ.  The hard measure-theoretic input is mathlib's ergodicity theorem for
`y ↦ b • y` on the additive circle.  Thus a closed positive-Haar-measure set
carried into itself by this map is almost full by ergodicity, then literally
full because Haar measure is positive on nonempty open sets.

The named hypothesis `LnTwoHypothesisLambda` is a `Prop`, not a Lean axiom.
Its implication to binary disjunctivity is proved at the end of the file.
-/

namespace NormalNumbers

open Filter Set Function MeasureTheory Topology
open scoped omegaLimit MeasureTheory

/-- The endpoint-identified unit interval used by the disjunctive orbit. -/
abbrev DisjunctiveCircle := UnitAddCircle

/-- Multiplication by `b` on the endpoint-identified unit interval. -/
def circleMap (b : ℕ) : DisjunctiveCircle → DisjunctiveCircle := fun y => b • y

theorem continuous_circleMap (b : ℕ) : Continuous (circleMap b) := by
  unfold circleMap
  exact continuous_nsmul b

/-- The continuous natural-number flow generated by multiplication by `b`. -/
noncomputable def circleFlow (b : ℕ) : Flow ℕ DisjunctiveCircle :=
  Flow.fromIter (continuous_circleMap b)

@[simp]
theorem circleFlow_apply (b n : ℕ) (y : DisjunctiveCircle) :
    circleFlow b n y = (b ^ n) • y := by
  induction n with
  | zero => simp [circleFlow]
  | succ n ih =>
      rw [show circleFlow b (n + 1) y = circleMap b (circleFlow b n y) by
        simp [circleFlow, Function.iterate_succ_apply']]
      rw [ih]
      simp only [circleMap, smul_smul]
      rw [Nat.pow_succ']

/-- The multiply-by-`b` orbit, now valued in the endpoint-identified circle. -/
noncomputable def circleOrbit (b : ℕ) (x : ℝ) (n : ℕ) : DisjunctiveCircle :=
  circleFlow b n (x : DisjunctiveCircle)

/-- The circle-valued orbit is the quotient of the existing `[0,1)` representative. -/
@[simp]
theorem circleOrbit_eq_coe_orbit (b : ℕ) (x : ℝ) (n : ℕ) :
    circleOrbit b x n = (orbit b x n : DisjunctiveCircle) := by
  rw [circleOrbit, circleFlow_apply]
  unfold orbit
  rw [AddCircle.coe_fract]
  rw [← AddCircle.coe_nsmul]
  simp [nsmul_eq_mul, mul_comm]

/-- Subsequential limits of the circle-valued multiply-by-`b` orbit. -/
noncomputable def circleOmegaLimit (b : ℕ) (x : ℝ) : Set DisjunctiveCircle :=
  omegaLimit atTop (circleFlow b) {(x : DisjunctiveCircle)}

theorem isClosed_circleOmegaLimit (b : ℕ) (x : ℝ) :
    IsClosed (circleOmegaLimit b x) := by
  unfold circleOmegaLimit
  exact isClosed_omegaLimit _ _ _

theorem isInvariant_circleOmegaLimit (b : ℕ) (x : ℝ) :
    IsInvariant (circleFlow b) (circleOmegaLimit b x) := by
  apply Flow.isInvariant_omegaLimit atTop (circleFlow b) {(x : DisjunctiveCircle)}
  intro t
  simpa [Nat.add_comm] using tendsto_add_atTop_nat t

/-- The ω-limit set is forward-invariant under one multiplication by `b`. -/
theorem mapsTo_circleMap_circleOmegaLimit (b : ℕ) (x : ℝ) :
    MapsTo (circleMap b) (circleOmegaLimit b x) (circleOmegaLimit b x) := by
  have hone : circleFlow b 1 = circleMap b := by
    funext y
    simp [circleMap]
  rw [← hone]
  exact isInvariant_circleOmegaLimit b x 1

private theorem unitAddCircle_nontrivial : Nontrivial DisjunctiveCircle := by
  apply nontrivial_of_ne (0 : DisjunctiveCircle) ((1 / 2 : ℝ) : DisjunctiveCircle)
  intro h
  have h' : (((1 / 2 : ℝ) : DisjunctiveCircle) = 0) := h.symm
  rw [AddCircle.coe_eq_zero_iff_of_mem_Ico] at h'
  · norm_num at h'
  · constructor <;> norm_num

private theorem denseRange_circleOrbit_of_isDisjunctive {b : ℕ} {x : ℝ}
    (h : IsDisjunctive b x) : DenseRange (circleOrbit b x) := by
  have hd := (isDisjunctive_iff_denseOrbit b x).1 h
  intro y
  obtain ⟨r, hr, rfl⟩ := AddCircle.eq_coe_Ico y
  have hrcl : r ∈ closure (range (orbit b x)) := hd hr
  have hmap : (r : DisjunctiveCircle) ∈
      closure (((↑) : ℝ → DisjunctiveCircle) '' range (orbit b x)) :=
    map_mem_closure (AddCircle.continuous_mk' 1) hrcl (mapsTo_image _ _)
  apply closure_mono _ hmap
  rintro _ ⟨_, ⟨n, rfl⟩, rfl⟩
  exact ⟨n, circleOrbit_eq_coe_orbit b x n⟩

private theorem isDisjunctive_of_denseRange_circleOrbit {b : ℕ} {x : ℝ}
    (h : DenseRange (circleOrbit b x)) : IsDisjunctive b x := by
  intro a c ha hac hc
  let y : ℝ := (a + c) / 2
  have hya : a < y := by simp only [y]; linarith
  have hyc : y < c := by simp only [y]; linarith
  have hyIco : y ∈ Ico (0 : ℝ) 1 :=
    ⟨le_of_lt (lt_of_le_of_lt ha hya), lt_of_lt_of_le hyc hc⟩
  have hyne : (y : DisjunctiveCircle) ≠ 0 := by
    intro hzero
    rw [AddCircle.coe_eq_zero_iff_of_mem_Ico hyIco] at hzero
    linarith
  let V : Set (Ico (0 : ℝ) (0 + 1)) := Subtype.val ⁻¹' Ioo a c
  have hVopen : IsOpen V := isOpen_Ioo.preimage continuous_subtype_val
  have hyV : AddCircle.equivIco 1 0 (y : DisjunctiveCircle) ∈ V := by
    change (AddCircle.equivIco 1 0 (y : DisjunctiveCircle) : ℝ) ∈ Ioo a c
    rw [AddCircle.equivIco_coe_of_mem (by simpa using hyIco)]
    exact ⟨hya, hyc⟩
  have hpre : (AddCircle.equivIco 1 0) ⁻¹' V ∈ 𝓝 (y : DisjunctiveCircle) :=
    (AddCircle.continuousAt_equivIco (𝕜 := ℝ) 1 0 hyne).preimage_mem_nhds
      (hVopen.mem_nhds hyV)
  obtain ⟨z, hzpre, hzrange⟩ :=
    (mem_closure_iff_nhds.mp (h (y : DisjunctiveCircle))) _ hpre
  obtain ⟨n, rfl⟩ := hzrange
  change (AddCircle.equivIco 1 0 (circleOrbit b x n) : ℝ) ∈ Ioo a c at hzpre
  rw [circleOrbit_eq_coe_orbit,
    AddCircle.equivIco_coe_of_mem (by simpa using orbit_mem_Ico b x n)] at hzpre
  exact ⟨n, le_of_lt hzpre.1, hzpre.2⟩

/-- Disjunctivity is density of the circle-valued orbit. -/
theorem isDisjunctive_iff_denseRange_circleOrbit (b : ℕ) (x : ℝ) :
    IsDisjunctive b x ↔ DenseRange (circleOrbit b x) :=
  ⟨denseRange_circleOrbit_of_isDisjunctive,
    isDisjunctive_of_denseRange_circleOrbit⟩

private theorem denseRange_tail {s : ℕ → DisjunctiveCircle} (hs : DenseRange s) (N : ℕ) :
    DenseRange fun n => s (N + n) := by
  let _ : Nontrivial DisjunctiveCircle := unitAddCircle_nontrivial
  let _ : PerfectSpace DisjunctiveCircle := inferInstance
  have hd : Dense (range s \ (s '' Iio N)) :=
    hs.sdiff_finite ((Set.finite_Iio N).image s)
  apply hd.mono
  rintro _ ⟨⟨n, rfl⟩, hn⟩
  have hNn : N ≤ n := by
    by_contra hnot
    exact hn ⟨n, Nat.lt_of_not_ge hnot, rfl⟩
  refine ⟨n - N, ?_⟩
  change s (N + (n - N)) = s n
  rw [Nat.add_sub_of_le hNn]

private theorem circleOmegaLimit_eq_univ_of_denseRange {b : ℕ} {x : ℝ}
    (h : DenseRange (circleOrbit b x)) : circleOmegaLimit b x = univ := by
  apply eq_univ_of_forall
  intro y
  apply (mem_omegaLimit_singleton_iff_mapClusterPt atTop (circleFlow b)
    (x : DisjunctiveCircle) y).2
  rw [mapClusterPt_iff_frequently]
  intro U hU
  rw [frequently_atTop]
  intro N
  obtain ⟨V, hVU, hVopen, hyV⟩ := mem_nhds_iff.mp hU
  have hycl := denseRange_tail h N y
  obtain ⟨z, hzV, hzrange⟩ :=
    mem_closure_iff.mp hycl V hVopen hyV
  obtain ⟨n, rfl⟩ := hzrange
  refine ⟨N + n, Nat.le_add_right N n, ?_⟩
  exact hVU (by simpa [circleOrbit] using hzV)

private theorem denseRange_circleOrbit_of_circleOmegaLimit_eq_univ {b : ℕ} {x : ℝ}
    (h : circleOmegaLimit b x = univ) : DenseRange (circleOrbit b x) := by
  intro y
  have hy : y ∈ circleOmegaLimit b x := by rw [h]; trivial
  have hy' := omegaLimit_subset_closure_image2 atTop (circleFlow b)
    ({(x : DisjunctiveCircle)} : Set DisjunctiveCircle) univ_mem hy
  change y ∈ closure (range fun n => circleFlow b n (x : DisjunctiveCircle))
  simpa only [Set.image2_singleton_right, image_univ] using hy'

/-- The endpoint-safe ω-limit formulation of disjunctivity. -/
theorem isDisjunctive_iff_circleOmegaLimit_eq_univ (b : ℕ) (x : ℝ) :
    IsDisjunctive b x ↔ circleOmegaLimit b x = univ := by
  rw [isDisjunctive_iff_denseRange_circleOrbit]
  exact ⟨circleOmegaLimit_eq_univ_of_denseRange,
    denseRange_circleOrbit_of_circleOmegaLimit_eq_univ⟩

/-- Closed positive-volume sets forward-invariant under multiplication by `b ≥ 2`
are the whole circle. -/
theorem closed_forwardInvariant_eq_univ_of_volume_pos (b : ℕ) (hb : 2 ≤ b)
    {K : Set DisjunctiveCircle} (hK : IsClosed K) (hforward : MapsTo (circleMap b) K K)
    (hpos : 0 < volume K) : K = univ := by
  have hsub : circleMap b '' K ⊆ K := hforward.image_subset
  have hae : circleMap b '' K ≤ᵐ[volume] K := Eventually.of_forall hsub
  have hergodic : Ergodic (circleMap b) volume := by
    unfold circleMap
    exact AddCircle.ergodic_nsmul (by omega)
  rcases hergodic.ae_empty_or_univ_of_image_ae_le
      hK.measurableSet.nullMeasurableSet hae with hempty | huniv
  · have hzero : volume K = 0 := ae_eq_empty.mp hempty
    exact ((ne_of_gt hpos) hzero).elim
  · exact (hK.ae_eq_univ_iff_eq).mp huniv

/-- Positive Haar mass of the ω-limit set forces disjunctivity. -/
theorem isDisjunctive_of_circleOmegaLimit_volume_pos (b : ℕ) (hb : 2 ≤ b) (x : ℝ)
    (hpos : 0 < volume (circleOmegaLimit b x)) : IsDisjunctive b x := by
  apply (isDisjunctive_iff_circleOmegaLimit_eq_univ b x).2
  exact closed_forwardInvariant_eq_univ_of_volume_pos b hb
    (isClosed_circleOmegaLimit b x) (mapsTo_circleMap_circleOmegaLimit b x) hpos

/-- The positive-mass hypothesis is equivalent to disjunctivity. -/
theorem circleOmegaLimit_volume_pos_iff_isDisjunctive (b : ℕ) (hb : 2 ≤ b) (x : ℝ) :
    0 < volume (circleOmegaLimit b x) ↔ IsDisjunctive b x := by
  constructor
  · exact isDisjunctive_of_circleOmegaLimit_volume_pos b hb x
  · intro h
    rw [(isDisjunctive_iff_circleOmegaLimit_eq_univ b x).1 h]
    simp [AddCircle.measure_univ]

/-- **Axiom Λ for `ln 2`**, encoded as a named hypothesis rather than a Lean axiom:
the doubling-orbit ω-limit has positive Haar measure. -/
def LnTwoHypothesisLambda : Prop :=
  0 < volume (circleOmegaLimit 2 (Real.log 2))

/-- Axiom Λ implies that `ln 2` is disjunctive in base two. -/
theorem isDisjunctive_log_two_of_hypothesisLambda
    (hΛ : LnTwoHypothesisLambda) : IsDisjunctive 2 (Real.log 2) :=
  isDisjunctive_of_circleOmegaLimit_volume_pos 2 (by omega) (Real.log 2) hΛ

end NormalNumbers
