/-
Copyright (c) 2026 Trevor Morris. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Trevor Morris
-/
import NormalNumbers.ExplicitSquareNonNormal
import Mathlib.Topology.MetricSpace.HausdorffDimension
import Mathlib.MeasureTheory.Measure.Hausdorff
import Mathlib.NumberTheory.Transcendental.Liouville.Basic

/-!
# Bergelson–Downarowicz open questions 2 and 4 (deterministic numbers)

Source: V. Bergelson, T. Downarowicz, *On preservation of normality and determinism under
arithmetic operations*, arXiv:2506.12929v1 (2025-06-15, the only arXiv version on 2026-10-03),
§9.6 "Some natural open problems" (TeX label `S7`; theorem numbers below were computed from the
v1 TeX source `Final2.tex`, counter `thm` per section, and are given with their TeX labels):

> 2. Is the reciprocal of a nonzero deterministic number always deterministic?
>
> 4. Can any nonzero real number be represented as (i) the product, (ii) the ratio, or (iii) the
> product of reciprocals, of two deterministic numbers?

Answers frozen here (both **No**), direction in `docs/OPEN-PROBLEMS-SWEEP-2026-10-03.md` §1, §2.

* Item 2: `exists_deterministic_inv_not_deterministic`, `not_reciprocalQuestion`, proved from two
  cited B-D Props (`DetSub`, `DetSqNotDet`) by Hua's identity (`hua_witness`).  An independent
  route to `DetSqNotDet` via Manai 2606.08325 is `detSqNotDet_of_manai`.
* Item 4: `dimH_detProducts`, `dimH_detRatios`, `dimH_detRecipProducts` (each `= 0`), the null-set
  forms `volume_detProducts` etc., and `not_productQuestion`, `not_ratioQuestion`,
  `not_recipProductQuestion`.  These are proved from two `sorry` leaves:
  (a) `deterministic_subexp_cover` (deterministic numbers are a countable union of sets with
  subexponential `b`-adic cylinder counts) and (b) `dimH_prod_le_of_subexp` (a product of two such
  sets has `dimH ≤ 2ε`).  The assembly (c) is proved.
* Control: `not_dimH_prod_zero_of_dimH_zero` (from the Liouville Props) shows that leaf (b) cannot
  be weakened to "`dimH A = dimH B = 0`": Liouville numbers have `dimH 0` yet multiply onto
  `ℝ \ {0}` (Erdős 1962).  The proof must use the packing-type cylinder count.
-/

open Filter MeasureTheory Set

namespace NormalNumbers.Deterministic

open Classical in
/-- Upper density of `S ⊆ ℕ` is at most `ε`: `limsup |S ∩ [0,N)| / N ≤ ε`. -/
def UpperDensityLE (S : Set ℕ) (ε : ℝ) : Prop :=
  ∀ δ > 0, ∀ᶠ N in atTop, ((((Finset.range N).filter (· ∈ S)).card : ℕ) : ℝ) ≤ (ε + δ) * N

/-- Bergelson–Downarowicz 2506.12929v1 **Def. 3.6** (label `complexity`), the witness form: "a
family of blocks `F ⊂ Λ^m` ... and a set `𝕊 ⊂ ℕ` of upper density not exceeding `ε`, satisfying
`ω|_{[i,i+m-1]} ∈ F` for all `i ∉ 𝕊`".  `C_ω(ε, m)` is the least such `|F|`, so
`C_ω(ε,m) < K ↔ ∃ F, EpsCover ω ε m F ∧ |F| < K` (their Remark 3.7).  Extra lists in `F` (wrong
length or letters) only enlarge `|F|`, so allowing them changes nothing. -/
def EpsCover (ω : ℕ → ℕ) (ε : ℝ) (m : ℕ) (F : Finset (List ℕ)) : Prop :=
  ∃ S : Set ℕ, UpperDensityLE S ε ∧ ∀ i, i ∉ S → (List.ofFn fun j : Fin m => ω (i + j)) ∈ F

/-- B-D **Def. 3.8** (label `detb`): "`ω` has subexponential epsilon-complexity if for any `ε > 0`
there exists an `m ∈ ℕ` such that `C_ω(ε, m) < 2^{εm}`."  B-D **Thm. 3.9** (label `detdet`, Weiss
[W3, Lemma 8.9]; proof in their Appendix) shows this is equivalent to **Def. 3.5** (label `deta`,
Weiss's "completely deterministic": every measure quasi-generated by `ω` has entropy `0`), which is
the definition their corollaries are proved for. -/
def IsDeterministicSeq (ω : ℕ → ℕ) : Prop :=
  ∀ ε > 0, ∃ (m : ℕ) (F : Finset (List ℕ)), EpsCover ω ε m F ∧ (F.card : ℝ) < (2 : ℝ) ^ (ε * m)

/-- B-D **Def. 3.10** (label `detn`): "A real number `x` is deterministic in base `r` if its alias
`ω_r(x)` is a deterministic sequence."  The alias (B-D §2, eq. `expansion`) is the digit sequence
after the radix point, with the expansion ending in `0`s for `b`-adic rationals (§4.1); that is
`digitOf b (Int.fract x)`.  Any base `b ≥ 2`; B-D's §9 examples are base `2`. -/
def IsDeterministic (b : ℕ) (x : ℝ) : Prop :=
  IsDeterministicSeq (digitOf b (Int.fract x))

theorem isDeterministicSeq_zero : IsDeterministicSeq fun _ => 0 := by
  intro ε hε
  refine ⟨1, {[0]}, ⟨∅, ?_, ?_⟩, ?_⟩
  · intro δ hδ
    refine Eventually.of_forall fun N => ?_
    simp only [mem_empty_iff_false, Finset.filter_false, Finset.card_empty, Nat.cast_zero]
    positivity
  · intro i _
    simp
  · simpa using Real.one_lt_rpow (by norm_num : (1 : ℝ) < 2) hε

/-- Integers are deterministic (all digits of `Int.fract n = 0` are `0`). -/
theorem isDeterministic_intCast (b : ℕ) (n : ℤ) : IsDeterministic b n := by
  have h : digitOf b (Int.fract (n : ℝ)) = fun _ => 0 := by
    funext i; simp [digitOf]
  unfold IsDeterministic
  rw [h]
  exact isDeterministicSeq_zero

/-- Rationals are deterministic (eventually periodic digits; B-D Prop. 3.11, label `triv`, with
`𝕊 = ℕ`).  Confidence 97%.  English proof: the digit sequence of `q` is eventually periodic with
period `p`; for `m ≥ 1` the length-`m` windows starting after the preperiod take at most `p`
values, so `F` = those windows and `𝕊` = the finite preperiod give `C(ε, m) ≤ p < 2^{εm}` once
`m > log₂ p / ε`.  Not needed by the headlines; it locates content (`irrational_of_not_det_sq`). -/
theorem isDeterministic_ratCast (b : ℕ) (hb : 2 ≤ b) (q : ℚ) : IsDeterministic b q := by
  sorry

end NormalNumbers.Deterministic

namespace NormalNumbers.Literature.BergelsonDownarowicz

open NormalNumbers.Deterministic

/-- **B-D 2506.12929v1 Cor. 4.12(2)** (label `rrr`): "`𝒟(r) = 𝒟^⊥(r)`.  The set `𝒟(r)` is a
subgroup of `(ℝ,+)`."  Stated as closure under subtraction (weaker than the full statement).
Proved in B-D through the torus model (Cor. 4.11(4), label `rauzy`): the sum map is continuous on
`𝕋`, so carries are absorbed, and entropy is subadditive on joinings.  Transcribed through
Thm. 3.9 (`IsDeterministic` is their Def. 3.8, the corollary is about Def. 3.5). -/
def DetSub (b : ℕ) : Prop :=
  ∀ x y : ℝ, IsDeterministic b x → IsDeterministic b y → IsDeterministic b (x - y)

/-- **B-D Cor. 9.15** (label `x^2`): "The square of a deterministic number need not be
deterministic."  Base `2` (the construction, Thm. 9.11 `cex` and Prop. 9.13 `1/y`, is binary). -/
def DetSqNotDet : Prop :=
  ∃ s : ℝ, IsDeterministic 2 s ∧ ¬ IsDeterministic 2 (s ^ 2)

/-- **B-D Prop. 4.8(1),(4)** (label `nordet1`) with Thm. 3.9: a point is deterministic iff its
entropy exists and is `0`; a real is normal in base `r` iff its entropy exists and is `log r`.
Hence no normal number is deterministic. -/
def NormalNotDet (b : ℕ) : Prop :=
  ∀ x : ℝ, IsNormal b x → ¬ IsDeterministic b x

/-- **B-D open question 2** (§9.6), as a `Prop`.  `not_reciprocalQuestion` answers it. -/
def ReciprocalQuestion (b : ℕ) : Prop :=
  ∀ y : ℝ, y ≠ 0 → IsDeterministic b y → IsDeterministic b y⁻¹

/-- **B-D open question 4(i)**: every nonzero real is a product of two deterministic numbers. -/
def ProductQuestion (b : ℕ) : Prop :=
  ∀ z : ℝ, z ≠ 0 → ∃ y₁ y₂, IsDeterministic b y₁ ∧ IsDeterministic b y₂ ∧ z = y₁ * y₂

/-- **B-D open question 4(ii)**: ... a ratio.  (`z ≠ 0` forces `y₂ ≠ 0` under Lean's `x / 0 = 0`.) -/
def RatioQuestion (b : ℕ) : Prop :=
  ∀ z : ℝ, z ≠ 0 → ∃ y₁ y₂, IsDeterministic b y₁ ∧ IsDeterministic b y₂ ∧ z = y₁ / y₂

/-- **B-D open question 4(iii)**: ... a product of reciprocals. -/
def RecipProductQuestion (b : ℕ) : Prop :=
  ∀ z : ℝ, z ≠ 0 → ∃ y₁ y₂, IsDeterministic b y₁ ∧ IsDeterministic b y₂ ∧ z = y₁⁻¹ * y₂⁻¹

end NormalNumbers.Literature.BergelsonDownarowicz

namespace NormalNumbers.Literature.Manai2026

open NormalNumbers.ExplicitSquare

/-- **Consequence of Manai 2606.08325v1 Cor. 1.4** (label `cor:quadratic-log`): for
`X = Σ ξ_n 2^{-n}` with independent `ξ_n ~ Bernoulli(p_n)` and
`v_n = p_n(1-p_n) ≥ A (log n / n)^{1/2}` (`A ≥ A₀`), `X²` is almost surely absolutely normal.
Taking `p_n → 0` at that rate, the digit-1 frequency of `X` is a.s. `0` (Kolmogorov's SLLN).
⚠️ That second conjunct is a routine probability step **not stated by Manai**; base-2 normality
is weaker than his absolute normality. -/
def QuadraticLogWitness : Prop :=
  ∃ X : ℝ, OneFreqZero X ∧ IsNormal 2 (X ^ 2)

end NormalNumbers.Literature.Manai2026

namespace NormalNumbers.Literature.Liouville

/-- **Erdős 1962** (P. Erdős, *Representations of real numbers as sums and products of Liouville
numbers*, Michigan Math. J. 9 (1962) 59–60): every nonzero real is a product of two Liouville
numbers (product half of the paper; the sum half is not used). -/
def Erdos1962Product : Prop :=
  ∀ z : ℝ, z ≠ 0 → ∃ x y : ℝ, _root_.Liouville x ∧ _root_.Liouville y ∧ z = x * y

/-- Classical: the Liouville numbers have Hausdorff dimension `0` (Jarník; e.g. Oxtoby, *Measure
and Category*, ch. 2 "Liouville numbers": `h`-measure zero for every dimension function). -/
def DimHZero : Prop :=
  dimH {x : ℝ | _root_.Liouville x} = 0

end NormalNumbers.Literature.Liouville

namespace NormalNumbers.Deterministic

open NormalNumbers.Literature.BergelsonDownarowicz

/-! ## Item 2: Hua's identity -/

/-- **Hua's identity inside `𝒟(b)`.**  If `𝒟(b)` is closed under subtraction and `s ∈ 𝒟(b)` has
`s² ∉ 𝒟(b)`, then one of `s`, `s + 1`, `1/(s(s+1))` is a nonzero deterministic number with
non-deterministic reciprocal.  (`1/s − 1/(s+1) = 1/(s(s+1))`, whose reciprocal is `s² + s`.) -/
theorem hua_witness {b : ℕ} (hsub : DetSub b) {s : ℝ}
    (hs : IsDeterministic b s) (hs2 : ¬ IsDeterministic b (s ^ 2)) :
    ∃ y ∈ ({s, s + 1, (s * (s + 1))⁻¹} : Set ℝ),
      y ≠ 0 ∧ IsDeterministic b y ∧ ¬ IsDeterministic b y⁻¹ := by
  have h0 : IsDeterministic b 0 := by simpa using isDeterministic_intCast b 0
  have h1 : IsDeterministic b 1 := by simpa using isDeterministic_intCast b 1
  have hadd : ∀ x y, IsDeterministic b x → IsDeterministic b y → IsDeterministic b (x + y) := by
    intro x y hx hy
    simpa using hsub x (0 - y) hx (hsub 0 y h0 hy)
  have hs0 : s ≠ 0 := by
    rintro rfl; exact hs2 (by simpa using h0)
  have hs10 : s + 1 ≠ 0 := by
    intro h
    have : s = -1 := by linarith
    subst this; exact hs2 (by norm_num; exact h1)
  have hs1 : IsDeterministic b (s + 1) := hadd _ _ hs h1
  by_contra hcon
  push_neg at hcon
  have hi1 := hcon s (by simp) hs0 hs
  have hi2 := hcon (s + 1) (by simp) hs10 hs1
  have hu : IsDeterministic b (s * (s + 1))⁻¹ := by
    have := hsub _ _ hi1 hi2
    convert this using 1
    field_simp
    ring
  have hu0 : (s * (s + 1))⁻¹ ≠ 0 := inv_ne_zero (mul_ne_zero hs0 hs10)
  have hui := hcon _ (by simp) hu0 hu
  rw [inv_inv] at hui
  apply hs2
  convert hsub _ _ hui hs using 1
  ring

/-- **Answer to Bergelson–Downarowicz question 2: No.**  Some nonzero base-2 deterministic number
has a non-deterministic reciprocal.  From B-D Cor. 4.12(2) and Cor. 9.15. -/
theorem exists_deterministic_inv_not_deterministic (hsub : DetSub 2) (hsq : DetSqNotDet) :
    ∃ y : ℝ, y ≠ 0 ∧ IsDeterministic 2 y ∧ ¬ IsDeterministic 2 y⁻¹ := by
  obtain ⟨s, hs, hs2⟩ := hsq
  obtain ⟨y, -, hy⟩ := hua_witness hsub hs hs2
  exact ⟨y, hy⟩

/-- B-D question 2, negated. -/
theorem not_reciprocalQuestion (hsub : DetSub 2) (hsq : DetSqNotDet) :
    ¬ ReciprocalQuestion 2 := by
  intro h
  obtain ⟨y, hy0, hy, hny⟩ := exists_deterministic_inv_not_deterministic hsub hsq
  exact hny (h y hy0 hy)

/-- Content locator: the premise `s² ∉ 𝒟` forces `s` irrational (rationals are deterministic). -/
theorem irrational_of_not_det_sq {b : ℕ} (hb : 2 ≤ b) {s : ℝ}
    (hs2 : ¬ IsDeterministic b (s ^ 2)) : Irrational s := by
  rintro ⟨q, rfl⟩
  have h := isDeterministic_ratCast b hb (q ^ 2)
  rw [Rat.cast_pow] at h
  exact hs2 h

/-- Digit-1 frequency `0` implies determinism (blocks `{0^m}`, bad set = windows meeting a `1`,
upper density `≤ m · 0`).  Confidence 97%.  English proof: given `ε`, take `m = 1`, `F = {[0]}`,
`𝕊 = {i : digit i = 1}`, which has density `0` by `OneFreqZero`; `1 < 2^ε`. -/
theorem isDeterministic_of_oneFreqZero {y : ℝ} (hy : ExplicitSquare.OneFreqZero y) :
    IsDeterministic 2 y := by
  sorry

/-- Independent route to B-D Cor. 9.15 through Manai 2606.08325 Cor. 1.4. -/
theorem detSqNotDet_of_manai (hM : Literature.Manai2026.QuadraticLogWitness)
    (hN : NormalNotDet 2) : DetSqNotDet := by
  obtain ⟨X, hX, hX2⟩ := hM
  exact ⟨X, isDeterministic_of_oneFreqZero hX, hN _ hX2⟩

/-! ## Item 4: products, ratios, reciprocal products have `dimH 0` -/

/-- `A` is covered, at every scale `b^{-N}` with `N ≥ N₀`, by at most `b^{εN}` `b`-adic intervals
`[t/b^N, (t+1)/b^N)` (so `A` is bounded and has upper box dimension `≤ ε`). -/
def SubexpCylinderCount (b : ℕ) (ε : ℝ) (A : Set ℝ) : Prop :=
  ∃ N₀ : ℕ, ∀ N ≥ N₀, ∃ T : Finset ℤ, (T.card : ℝ) ≤ (b : ℝ) ^ (ε * N) ∧
    A ⊆ ⋃ t ∈ T, Ico ((t : ℝ) / (b : ℝ) ^ N) (((t : ℝ) + 1) / (b : ℝ) ^ N)

/-- **Leaf (a): `𝒟(b)` has packing dimension `0`.**  Confidence 85%.

English proof.  Fix `ε > 0`; pick `ε' > 0` with `H(2ε') + ε' + 2ε' log₂ b < ε log₂ b`
(`H` the binary entropy).  For `x ∈ 𝒟(b)` Def. 3.8 at `ε'` gives `m ≥ 1`, `F` with
`|F| < 2^{ε'm}` and `𝕊` of upper density `≤ ε'`, so `|𝕊 ∩ [0,N)| ≤ 2ε'N` for `N ≥ N₀`.  Index the
pieces by `(k, m, F, N₀) ∈ ℤ × ℕ × Finset (List ℕ) × ℕ` (countable): the set of `x ∈ [k, k+1)`
whose digit windows at positions outside some `𝕊'` with `|𝕊' ∩ [0,N)| ≤ 2ε'N` (all `N ≥ N₀`) lie
in `F`.  A length-`N` prefix of such `x` is fixed by: a phase `φ < m` with at most `2ε'N/m` bad
aligned windows in `φ + mℕ` (pigeonhole), the first `φ` digits (`b^m`), which aligned windows are
bad (`≤ 2^{(N/m) H(2ε')}`), the good windows (`|F|^{N/m} ≤ 2^{ε'N}`), the bad windows
(`b^{2ε'N}`) and the last `< m` digits (`b^m`).  The product is `≤ m b^{2m} 2^{N(H(2ε')+ε')} b^{2ε'N}
≤ b^{εN}` for `N` large.  Each prefix is one `b`-adic interval of rank `N`, shifted by `k`. -/
theorem deterministic_subexp_cover (b : ℕ) (hb : 2 ≤ b) (ε : ℝ) (hε : 0 < ε) :
    ∃ E : ℕ → Set ℝ, (∀ i, SubexpCylinderCount b ε (E i)) ∧
      {x : ℝ | IsDeterministic b x} ⊆ ⋃ i, E i := by
  sorry

/-- **Leaf (b): box-counting bound for a product.**  Confidence 92%.

English proof.  For `N ≥ max N₀_A N₀_B`, `A ×ˢ B` is covered by `|T_A| |T_B| ≤ b^{2εN}` squares
`[s/b^N, (s+1)/b^N) × [t/b^N, (t+1)/b^N)`, each of sup-metric diameter `b^{-N}`.  For `d > 2ε`,
`μH[d](A ×ˢ B) ≤ liminf_N b^{2εN} b^{-dN} = 0`, so `dimH (A ×ˢ B) ≤ d`.  Only the *every large
scale* count is used; `dimH A = dimH B = 0` alone is not enough (`not_dimH_prod_zero_of_dimH_zero`).
-/
theorem dimH_prod_le_of_subexp {b : ℕ} (hb : 2 ≤ b) {ε : ℝ} (hε : 0 ≤ ε) {A B : Set ℝ}
    (hA : SubexpCylinderCount b ε A) (hB : SubexpCylinderCount b ε B) :
    dimH (A ×ˢ B) ≤ ENNReal.ofReal (2 * ε) := by
  sorry

/-- A map that is `C¹` at every point of `s` does not raise Hausdorff dimension on `s`. -/
theorem dimH_image_le_of_contDiffAt {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [FiniteDimensional ℝ E] [NormedAddCommGroup F] [NormedSpace ℝ F] {f : E → F} {s : Set E}
    (hf : ∀ x ∈ s, ContDiffAt ℝ 1 f x) : dimH (f '' s) ≤ dimH s :=
  dimH_image_le_of_locally_lipschitzOn fun x hx =>
    let ⟨K, t, ht, hK⟩ := (hf x hx).exists_lipschitzOnWith
    ⟨K, t, mem_nhdsWithin_of_mem_nhds ht, hK⟩

/-- If `dimH s ≤ 2ε` for every `ε > 0` then `dimH s = 0`. -/
theorem dimH_eq_zero_of_forall {X : Type*} [EMetricSpace X] {s : Set X}
    (h : ∀ ε : ℝ, 0 < ε → dimH s ≤ ENNReal.ofReal (2 * ε)) : dimH s = 0 := by
  refine le_antisymm (ENNReal.le_of_forall_pos_le_add fun ε hε _ => ?_) zero_le
  have := h ((ε : ℝ) / 2) (by positivity)
  rw [zero_add]
  convert this using 1
  rw [mul_div_cancel₀ _ (two_ne_zero), ENNReal.ofReal_coe_nnreal]

/-- The set of products of two base-`b` deterministic numbers. -/
def detProducts (b : ℕ) : Set ℝ :=
  {z | ∃ y₁ y₂, IsDeterministic b y₁ ∧ IsDeterministic b y₂ ∧ z = y₁ * y₂}

/-- The set of ratios of two base-`b` deterministic numbers. -/
def detRatios (b : ℕ) : Set ℝ :=
  {z | ∃ y₁ y₂, IsDeterministic b y₁ ∧ IsDeterministic b y₂ ∧ z = y₁ / y₂}

/-- The set of products of reciprocals of two base-`b` deterministic numbers. -/
def detRecipProducts (b : ℕ) : Set ℝ :=
  {z | ∃ y₁ y₂, IsDeterministic b y₁ ∧ IsDeterministic b y₂ ∧ z = y₁⁻¹ * y₂⁻¹}

/-- **(c), products: `dimH (𝒟·𝒟) = 0`.**  From leaves (a), (b). -/
theorem dimH_detProducts (b : ℕ) (hb : 2 ≤ b) : dimH (detProducts b) = 0 := by
  refine dimH_eq_zero_of_forall fun ε hε => ?_
  obtain ⟨E, hE, hcov⟩ := deterministic_subexp_cover b hb ε hε
  have hsub : detProducts b ⊆ ⋃ i, ⋃ j, image2 (· * ·) (E i) (E j) := by
    rintro z ⟨y₁, y₂, h₁, h₂, rfl⟩
    obtain ⟨i, hi⟩ := mem_iUnion.1 (hcov h₁)
    obtain ⟨j, hj⟩ := mem_iUnion.1 (hcov h₂)
    exact mem_iUnion.2 ⟨i, mem_iUnion.2 ⟨j, mem_image2_of_mem hi hj⟩⟩
  refine (dimH_mono hsub).trans ?_
  simp only [dimH_iUnion]
  refine iSup_le fun i => iSup_le fun j => ?_
  rw [← image_uncurry_prod]
  refine (dimH_image_le_of_contDiffAt fun p _ => ?_).trans
    (dimH_prod_le_of_subexp hb hε.le (hE i) (hE j))
  exact (contDiffAt_fst.mul contDiffAt_snd : ContDiffAt ℝ 1 (fun p : ℝ × ℝ => p.1 * p.2) p)

/-- **(c), ratios: `dimH (𝒟/𝒟) = 0`.** -/
theorem dimH_detRatios (b : ℕ) (hb : 2 ≤ b) : dimH (detRatios b) = 0 := by
  refine dimH_eq_zero_of_forall fun ε hε => ?_
  obtain ⟨E, hE, hcov⟩ := deterministic_subexp_cover b hb ε hε
  have hsub : detRatios b ⊆ {0} ∪ ⋃ i, ⋃ j, image2 (· / ·) (E i) (E j \ {0}) := by
    rintro z ⟨y₁, y₂, h₁, h₂, rfl⟩
    by_cases hy : y₂ = 0
    · left; simp [hy]
    right
    obtain ⟨i, hi⟩ := mem_iUnion.1 (hcov h₁)
    obtain ⟨j, hj⟩ := mem_iUnion.1 (hcov h₂)
    exact mem_iUnion.2 ⟨i, mem_iUnion.2 ⟨j, mem_image2_of_mem hi ⟨hj, hy⟩⟩⟩
  refine (dimH_mono hsub).trans ?_
  rw [dimH_union, dimH_singleton]
  simp only [dimH_iUnion]
  refine max_le zero_le (iSup_le fun i => iSup_le fun j => ?_)
  rw [← image_uncurry_prod]
  refine (dimH_image_le_of_contDiffAt fun p hp => ?_).trans
    ((dimH_mono (prod_mono subset_rfl sdiff_subset)).trans
      (dimH_prod_le_of_subexp hb hε.le (hE i) (hE j)))
  have hp2 : p.2 ≠ 0 := hp.2.2
  exact (contDiffAt_fst.div contDiffAt_snd hp2 : ContDiffAt ℝ 1 (fun p : ℝ × ℝ => p.1 / p.2) p)

/-- **(c), reciprocal products: `dimH ((𝒟·𝒟)⁻¹) = 0`.**  `y₁⁻¹ y₂⁻¹ = (y₁ y₂)⁻¹`, and inversion is
`C¹` off `0`. -/
theorem dimH_detRecipProducts (b : ℕ) (hb : 2 ≤ b) : dimH (detRecipProducts b) = 0 := by
  have hsub : detRecipProducts b ⊆ {0} ∪ (fun z : ℝ => z⁻¹) '' (detProducts b \ {0}) := by
    rintro z ⟨y₁, y₂, h₁, h₂, rfl⟩
    by_cases h : y₁ * y₂ = 0
    · left; simp [← mul_inv, h]
    · right; exact ⟨y₁ * y₂, ⟨⟨y₁, y₂, h₁, h₂, rfl⟩, h⟩, by show (y₁ * y₂)⁻¹ = _; exact mul_inv y₁ y₂⟩
  refine le_antisymm ((dimH_mono hsub).trans ?_) zero_le
  rw [dimH_union, dimH_singleton]
  refine max_le zero_le ?_
  refine (dimH_image_le_of_contDiffAt fun z hz => contDiffAt_inv ℝ hz.2).trans ?_
  exact (dimH_mono sdiff_subset).trans (dimH_detProducts b hb).le

/-- `dimH s = 0` makes `s` Lebesgue-null. -/
theorem volume_eq_zero_of_dimH_eq_zero {s : Set ℝ} (h : dimH s = 0) : volume s = 0 := by
  have := hausdorffMeasure_of_dimH_lt (s := s) (d := 1) (by rw [h]; norm_num)
  rwa [NNReal.coe_one, hausdorffMeasure_real] at this

/-- `dimH s = 0` leaves a positive real outside `s`. -/
theorem exists_pos_not_mem_of_dimH_eq_zero {s : Set ℝ} (h : dimH s = 0) : ∃ z : ℝ, 0 < z ∧ z ∉ s := by
  have hd : Dense sᶜ := dense_compl_of_dimH_lt_finrank (by rw [h]; simp)
  obtain ⟨z, hz, hzs⟩ := hd.inter_open_nonempty (Ioi 0) isOpen_Ioi ⟨1, by norm_num⟩
  exact ⟨z, hz, hzs⟩

/-- **B-D question 4(i): No** (Lebesgue form). -/
theorem volume_detProducts (b : ℕ) (hb : 2 ≤ b) : volume (detProducts b) = 0 :=
  volume_eq_zero_of_dimH_eq_zero (dimH_detProducts b hb)

/-- **B-D question 4(ii): No** (Lebesgue form). -/
theorem volume_detRatios (b : ℕ) (hb : 2 ≤ b) : volume (detRatios b) = 0 :=
  volume_eq_zero_of_dimH_eq_zero (dimH_detRatios b hb)

/-- **B-D question 4(iii): No** (Lebesgue form). -/
theorem volume_detRecipProducts (b : ℕ) (hb : 2 ≤ b) : volume (detRecipProducts b) = 0 :=
  volume_eq_zero_of_dimH_eq_zero (dimH_detRecipProducts b hb)

/-- **Answer to B-D question 4(i): No.** -/
theorem not_productQuestion (b : ℕ) (hb : 2 ≤ b) : ¬ ProductQuestion b := by
  intro h
  obtain ⟨z, hz, hzs⟩ := exists_pos_not_mem_of_dimH_eq_zero (dimH_detProducts b hb)
  exact hzs (h z hz.ne')

/-- **Answer to B-D question 4(ii): No.** -/
theorem not_ratioQuestion (b : ℕ) (hb : 2 ≤ b) : ¬ RatioQuestion b := by
  intro h
  obtain ⟨z, hz, hzs⟩ := exists_pos_not_mem_of_dimH_eq_zero (dimH_detRatios b hb)
  exact hzs (h z hz.ne')

/-- **Answer to B-D question 4(iii): No.** -/
theorem not_recipProductQuestion (b : ℕ) (hb : 2 ≤ b) : ¬ RecipProductQuestion b := by
  intro h
  obtain ⟨z, hz, hzs⟩ := exists_pos_not_mem_of_dimH_eq_zero (dimH_detRecipProducts b hb)
  exact hzs (h z hz.ne')

/-! ## Known-false sibling: Hausdorff dimension `0` alone does not suffice -/

/-- **Control for leaf (b).**  Given that Liouville numbers have `dimH 0` and multiply onto
`ℝ \ {0}` (Erdős 1962), the weakening of `dimH_prod_le_of_subexp` to hypotheses `dimH A = 0`,
`dimH B = 0` is false.  So the proof of item 4 must use the every-scale cylinder count of
`SubexpCylinderCount` (packing dimension `0`); the Liouville set is a dense `G_δ` of packing
dimension `1`. -/
theorem not_dimH_prod_zero_of_dimH_zero (hL : Literature.Liouville.DimHZero)
    (hE : Literature.Liouville.Erdos1962Product) :
    ¬ ∀ A B : Set ℝ, dimH A = 0 → dimH B = 0 → dimH (A ×ˢ B) = 0 := by
  intro h
  set L := {x : ℝ | _root_.Liouville x}
  have hprod := h L L hL hL
  have himg : dimH (image2 (· * ·) L L) = 0 := by
    refine le_antisymm ?_ zero_le
    rw [← image_uncurry_prod, ← hprod]
    exact dimH_image_le_of_contDiffAt fun p _ =>
      (contDiffAt_fst.mul contDiffAt_snd : ContDiffAt ℝ 1 (fun p : ℝ × ℝ => p.1 * p.2) p)
  obtain ⟨z, hz, hzs⟩ := exists_pos_not_mem_of_dimH_eq_zero himg
  obtain ⟨x, y, hx, hy, rfl⟩ := hE z hz.ne'
  exact hzs (mem_image2_of_mem hx hy)

end NormalNumbers.Deterministic
