/-
Copyright (c) 2026 Trevor Morris. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Trevor Morris
-/
import NormalNumbers.ExplicitSquareNonNormal
import NormalNumbers.DigitInterval
import Mathlib.Topology.MetricSpace.HausdorffDimension
import Mathlib.MeasureTheory.Measure.Hausdorff
import Mathlib.NumberTheory.Transcendental.Liouville.Basic

/-!
# Bergelson–Downarowicz open questions 2 and 4 (deterministic numbers)

Source: V. Bergelson, T. Downarowicz, *On preservation of normality and determinism under
arithmetic operations*, arXiv:2506.12929v1 (2025-06-15, the only arXiv version on 2026-10-03),
§9.6 "Some natural open problems" (TeX label `S7`; theorem numbers below were computed from the
v1 TeX source `Final2.tex`, counter `thm` per section, and are given with their TeX labels):

> 2. Is the reciprocal of a nonzero deterministic number always deterministic?
>
> 4. Can any nonzero real number be represented as (i) the product, (ii) the ratio, or (iii) the
> product of reciprocals, of two deterministic numbers?

Answers frozen here (both **No**), direction in `docs/OPEN-PROBLEMS-SWEEP-2026-10-03.md` §1, §2.

* Item 2: `exists_deterministic_inv_not_deterministic`, `not_reciprocalQuestion`, proved from two
  cited B-D Props (`DetSub`, `DetSqNotDet`) by Hua's identity (`hua_witness`).  An independent
  route to `DetSqNotDet` via Manai 2606.08325 is `detSqNotDet_of_manai`.
* Item 4: `dimH_detProducts`, `dimH_detRatios`, `dimH_detRecipProducts` (each `= 0`), the null-set
  forms `volume_detProducts` etc., and `not_productQuestion`, `not_ratioQuestion`,
  `not_recipProductQuestion`.  These are proved from two `sorry` leaves:
  (a) `deterministic_subexp_cover` (deterministic numbers are a countable union of sets with
  subexponential `b`-adic cylinder counts) and (b) `dimH_prod_le_of_subexp` (a product of two such
  sets has `dimH ≤ 2ε`).  The assembly (c) is proved.
* Control: `not_dimH_prod_zero_of_dimH_zero` (from the Liouville Props) shows that leaf (b) cannot
  be weakened to "`dimH A = dimH B = 0`": Liouville numbers have `dimH 0` yet multiply onto
  `ℝ \ {0}` (Erdős 1962).  The proof must use the packing-type cylinder count.
-/

open Filter MeasureTheory Set
open scoped ENNReal NNReal Topology

namespace NormalNumbers.Deterministic

open Classical in
/-- Upper density of `S ⊆ ℕ` is at most `ε`: `limsup |S ∩ [0,N)| / N ≤ ε`. -/
def UpperDensityLE (S : Set ℕ) (ε : ℝ) : Prop :=
  ∀ δ > 0, ∀ᶠ N in atTop, ((((Finset.range N).filter (· ∈ S)).card : ℕ) : ℝ) ≤ (ε + δ) * N

/-- Bergelson–Downarowicz 2506.12929v1 **Def. 3.6** (label `complexity`), the witness form: "a
family of blocks `F ⊂ Λ^m` ... and a set `𝕊 ⊂ ℕ` of upper density not exceeding `ε`, satisfying
`ω|_{[i,i+m-1]} ∈ F` for all `i ∉ 𝕊`".  `C_ω(ε, m)` is the least such `|F|`, so
`C_ω(ε,m) < K ↔ ∃ F, EpsCover ω ε m F ∧ |F| < K` (their Remark 3.7).  Extra lists in `F` (wrong
length or letters) only enlarge `|F|`, so allowing them changes nothing. -/
def EpsCover (ω : ℕ → ℕ) (ε : ℝ) (m : ℕ) (F : Finset (List ℕ)) : Prop :=
  ∃ S : Set ℕ, UpperDensityLE S ε ∧ ∀ i, i ∉ S → (List.ofFn fun j : Fin m => ω (i + j)) ∈ F

/-- B-D **Def. 3.8** (label `detb`): "`ω` has subexponential epsilon-complexity if for any `ε > 0`
there exists an `m ∈ ℕ` such that `C_ω(ε, m) < 2^{εm}`."  B-D **Thm. 3.9** (label `detdet`, Weiss
[W3, Lemma 8.9]; proof in their Appendix) shows this is equivalent to **Def. 3.5** (label `deta`,
Weiss's "completely deterministic": every measure quasi-generated by `ω` has entropy `0`), which is
the definition their corollaries are proved for. -/
def IsDeterministicSeq (ω : ℕ → ℕ) : Prop :=
  ∀ ε > 0, ∃ (m : ℕ) (F : Finset (List ℕ)), EpsCover ω ε m F ∧ (F.card : ℝ) < (2 : ℝ) ^ (ε * m)

/-- B-D **Def. 3.10** (label `detn`): "A real number `x` is deterministic in base `r` if its alias
`ω_r(x)` is a deterministic sequence."  The alias (B-D §2, eq. `expansion`) is the digit sequence
after the radix point, with the expansion ending in `0`s for `b`-adic rationals (§4.1); that is
`digitOf b (Int.fract x)`.  Any base `b ≥ 2`; B-D's §9 examples are base `2`. -/
def IsDeterministic (b : ℕ) (x : ℝ) : Prop :=
  IsDeterministicSeq (digitOf b (Int.fract x))

theorem isDeterministicSeq_zero : IsDeterministicSeq fun _ => 0 := by
  intro ε hε
  refine ⟨1, {[0]}, ⟨∅, ?_, ?_⟩, ?_⟩
  · intro δ hδ
    refine Eventually.of_forall fun N => ?_
    simp only [mem_empty_iff_false, Finset.filter_false, Finset.card_empty, Nat.cast_zero]
    positivity
  · intro i _
    simp
  · simpa using Real.one_lt_rpow (by norm_num : (1 : ℝ) < 2) hε

/-- Integers are deterministic (all digits of `Int.fract n = 0` are `0`). -/
theorem isDeterministic_intCast (b : ℕ) (n : ℤ) : IsDeterministic b n := by
  have h : digitOf b (Int.fract (n : ℝ)) = fun _ => 0 := by
    funext i; simp [digitOf]
  unfold IsDeterministic
  rw [h]
  exact isDeterministicSeq_zero

/-- Rationals are deterministic (eventually periodic digits; B-D Prop. 3.11, label `triv`, with
`𝕊 = ℕ`).  Confidence 97%.  English proof: the digit sequence of `q` is eventually periodic with
period `p`; for `m ≥ 1` the length-`m` windows starting after the preperiod take at most `p`
values, so `F` = those windows and `𝕊` = the finite preperiod give `C(ε, m) ≤ p < 2^{εm}` once
`m > log₂ p / ε`.  Not needed by the headlines; it locates content (`irrational_of_not_det_sq`). -/
theorem isDeterministic_ratCast (b : ℕ) (hb : 2 ≤ b) (q : ℚ) : IsDeterministic b q := by
  sorry

end NormalNumbers.Deterministic

namespace NormalNumbers.Literature.BergelsonDownarowicz

open NormalNumbers.Deterministic

/-- **B-D 2506.12929v1 Cor. 4.12(2)** (label `rrr`): "`𝒟(r) = 𝒟^⊥(r)`.  The set `𝒟(r)` is a
subgroup of `(ℝ,+)`."  Stated as closure under subtraction (weaker than the full statement).
Proved in B-D through the torus model (Cor. 4.11(4), label `rauzy`): the sum map is continuous on
`𝕋`, so carries are absorbed, and entropy is subadditive on joinings.  Transcribed through
Thm. 3.9 (`IsDeterministic` is their Def. 3.8, the corollary is about Def. 3.5). -/
def DetSub (b : ℕ) : Prop :=
  ∀ x y : ℝ, IsDeterministic b x → IsDeterministic b y → IsDeterministic b (x - y)

/-- **B-D Cor. 9.15** (label `x^2`): "The square of a deterministic number need not be
deterministic."  Base `2` (the construction, Thm. 9.11 `cex` and Prop. 9.13 `1/y`, is binary). -/
def DetSqNotDet : Prop :=
  ∃ s : ℝ, IsDeterministic 2 s ∧ ¬ IsDeterministic 2 (s ^ 2)

/-- **B-D Prop. 4.8(1),(4)** (label `nordet1`) with Thm. 3.9: a point is deterministic iff its
entropy exists and is `0`; a real is normal in base `r` iff its entropy exists and is `log r`.
Hence no normal number is deterministic. -/
def NormalNotDet (b : ℕ) : Prop :=
  ∀ x : ℝ, IsNormal b x → ¬ IsDeterministic b x

/-- **B-D open question 2** (§9.6), as a `Prop`.  `not_reciprocalQuestion` answers it. -/
def ReciprocalQuestion (b : ℕ) : Prop :=
  ∀ y : ℝ, y ≠ 0 → IsDeterministic b y → IsDeterministic b y⁻¹

/-- **B-D open question 4(i)**: every nonzero real is a product of two deterministic numbers. -/
def ProductQuestion (b : ℕ) : Prop :=
  ∀ z : ℝ, z ≠ 0 → ∃ y₁ y₂, IsDeterministic b y₁ ∧ IsDeterministic b y₂ ∧ z = y₁ * y₂

/-- **B-D open question 4(ii)**: ... a ratio.  (`z ≠ 0` forces `y₂ ≠ 0` under Lean's `x / 0 = 0`.) -/
def RatioQuestion (b : ℕ) : Prop :=
  ∀ z : ℝ, z ≠ 0 → ∃ y₁ y₂, IsDeterministic b y₁ ∧ IsDeterministic b y₂ ∧ z = y₁ / y₂

/-- **B-D open question 4(iii)**: ... a product of reciprocals. -/
def RecipProductQuestion (b : ℕ) : Prop :=
  ∀ z : ℝ, z ≠ 0 → ∃ y₁ y₂, IsDeterministic b y₁ ∧ IsDeterministic b y₂ ∧ z = y₁⁻¹ * y₂⁻¹

end NormalNumbers.Literature.BergelsonDownarowicz

namespace NormalNumbers.Literature.Manai2026

open NormalNumbers.ExplicitSquare

/-- **Consequence of Manai 2606.08325v1 Cor. 1.4** (label `cor:quadratic-log`): for
`X = Σ ξ_n 2^{-n}` with independent `ξ_n ~ Bernoulli(p_n)` and
`v_n = p_n(1-p_n) ≥ A (log n / n)^{1/2}` (`A ≥ A₀`), `X²` is almost surely absolutely normal.
Taking `p_n → 0` at that rate, the digit-1 frequency of `X` is a.s. `0` (Kolmogorov's SLLN).
⚠️ That second conjunct is a routine probability step **not stated by Manai**; base-2 normality
is weaker than his absolute normality. -/
def QuadraticLogWitness : Prop :=
  ∃ X : ℝ, OneFreqZero X ∧ IsNormal 2 (X ^ 2)

end NormalNumbers.Literature.Manai2026

namespace NormalNumbers.Literature.Liouville

/-- **Erdős 1962** (P. Erdős, *Representations of real numbers as sums and products of Liouville
numbers*, Michigan Math. J. 9 (1962) 59–60): every nonzero real is a product of two Liouville
numbers (product half of the paper; the sum half is not used). -/
def Erdos1962Product : Prop :=
  ∀ z : ℝ, z ≠ 0 → ∃ x y : ℝ, _root_.Liouville x ∧ _root_.Liouville y ∧ z = x * y

/-- Classical: the Liouville numbers have Hausdorff dimension `0` (Jarník; e.g. Oxtoby, *Measure
and Category*, ch. 2 "Liouville numbers": `h`-measure zero for every dimension function). -/
def DimHZero : Prop :=
  dimH {x : ℝ | _root_.Liouville x} = 0

end NormalNumbers.Literature.Liouville

namespace NormalNumbers.Deterministic

open NormalNumbers.Literature.BergelsonDownarowicz

/-! ## Item 2: Hua's identity -/

/-- **Hua's identity inside `𝒟(b)`.**  If `𝒟(b)` is closed under subtraction and `s ∈ 𝒟(b)` has
`s² ∉ 𝒟(b)`, then one of `s`, `s + 1`, `1/(s(s+1))` is a nonzero deterministic number with
non-deterministic reciprocal.  (`1/s − 1/(s+1) = 1/(s(s+1))`, whose reciprocal is `s² + s`.) -/
theorem hua_witness {b : ℕ} (hsub : DetSub b) {s : ℝ}
    (hs : IsDeterministic b s) (hs2 : ¬ IsDeterministic b (s ^ 2)) :
    ∃ y ∈ ({s, s + 1, (s * (s + 1))⁻¹} : Set ℝ),
      y ≠ 0 ∧ IsDeterministic b y ∧ ¬ IsDeterministic b y⁻¹ := by
  have h0 : IsDeterministic b 0 := by simpa using isDeterministic_intCast b 0
  have h1 : IsDeterministic b 1 := by simpa using isDeterministic_intCast b 1
  have hadd : ∀ x y, IsDeterministic b x → IsDeterministic b y → IsDeterministic b (x + y) := by
    intro x y hx hy
    simpa using hsub x (0 - y) hx (hsub 0 y h0 hy)
  have hs0 : s ≠ 0 := by
    rintro rfl; exact hs2 (by simpa using h0)
  have hs10 : s + 1 ≠ 0 := by
    intro h
    have : s = -1 := by linarith
    subst this; exact hs2 (by norm_num; exact h1)
  have hs1 : IsDeterministic b (s + 1) := hadd _ _ hs h1
  by_contra hcon
  push_neg at hcon
  have hi1 := hcon s (by simp) hs0 hs
  have hi2 := hcon (s + 1) (by simp) hs10 hs1
  have hu : IsDeterministic b (s * (s + 1))⁻¹ := by
    have := hsub _ _ hi1 hi2
    convert this using 1
    field_simp
    ring
  have hu0 : (s * (s + 1))⁻¹ ≠ 0 := inv_ne_zero (mul_ne_zero hs0 hs10)
  have hui := hcon _ (by simp) hu0 hu
  rw [inv_inv] at hui
  apply hs2
  convert hsub _ _ hui hs using 1
  ring

/-- **Answer to Bergelson–Downarowicz question 2: No.**  Some nonzero base-2 deterministic number
has a non-deterministic reciprocal.  From B-D Cor. 4.12(2) and Cor. 9.15. -/
theorem exists_deterministic_inv_not_deterministic (hsub : DetSub 2) (hsq : DetSqNotDet) :
    ∃ y : ℝ, y ≠ 0 ∧ IsDeterministic 2 y ∧ ¬ IsDeterministic 2 y⁻¹ := by
  obtain ⟨s, hs, hs2⟩ := hsq
  obtain ⟨y, -, hy⟩ := hua_witness hsub hs hs2
  exact ⟨y, hy⟩

/-- B-D question 2, negated. -/
theorem not_reciprocalQuestion (hsub : DetSub 2) (hsq : DetSqNotDet) :
    ¬ ReciprocalQuestion 2 := by
  intro h
  obtain ⟨y, hy0, hy, hny⟩ := exists_deterministic_inv_not_deterministic hsub hsq
  exact hny (h y hy0 hy)

/-- Content locator: the premise `s² ∉ 𝒟` forces `s` irrational (rationals are deterministic). -/
theorem irrational_of_not_det_sq {b : ℕ} (hb : 2 ≤ b) {s : ℝ}
    (hs2 : ¬ IsDeterministic b (s ^ 2)) : Irrational s := by
  rintro ⟨q, rfl⟩
  have h := isDeterministic_ratCast b hb (q ^ 2)
  rw [Rat.cast_pow] at h
  exact hs2 h

/-- Digit-1 frequency `0` implies determinism (blocks `{0^m}`, bad set = windows meeting a `1`,
upper density `≤ m · 0`).  Confidence 97%.  English proof: given `ε`, take `m = 1`, `F = {[0]}`,
`𝕊 = {i : digit i = 1}`, which has density `0` by `OneFreqZero`; `1 < 2^ε`. -/
theorem isDeterministic_of_oneFreqZero {y : ℝ} (hy : ExplicitSquare.OneFreqZero y) :
    IsDeterministic 2 y := by
  sorry

/-- Independent route to B-D Cor. 9.15 through Manai 2606.08325 Cor. 1.4. -/
theorem detSqNotDet_of_manai (hM : Literature.Manai2026.QuadraticLogWitness)
    (hN : NormalNotDet 2) : DetSqNotDet := by
  obtain ⟨X, hX, hX2⟩ := hM
  exact ⟨X, isDeterministic_of_oneFreqZero hX, hN _ hX2⟩

/-! ## Item 4: products, ratios, reciprocal products have `dimH 0` -/

/-- `A` is covered, at every scale `b^{-N}` with `N ≥ N₀`, by at most `b^{εN}` `b`-adic intervals
`[t/b^N, (t+1)/b^N)` (so `A` is bounded and has upper box dimension `≤ ε`). -/
def SubexpCylinderCount (b : ℕ) (ε : ℝ) (A : Set ℝ) : Prop :=
  ∃ N₀ : ℕ, ∀ N ≥ N₀, ∃ T : Finset ℤ, (T.card : ℝ) ≤ (b : ℝ) ^ (ε * N) ∧
    A ⊆ ⋃ t ∈ T, Ico ((t : ℝ) / (b : ℝ) ^ N) (((t : ℝ) + 1) / (b : ℝ) ^ N)

/-! ### Leaf (a): counting prefixes -/

/-- Candidate suffixes `w[i,N)`: an `F`-block at a good position with room for it, else any digit. -/
def candSuffix (b m N : ℕ) (T : Finset ℕ) (F : Finset (List ℕ)) (i : ℕ) : Finset (List ℕ) :=
  if N ≤ i then {[]}
  else if i ∉ T ∧ 0 < m ∧ i + m ≤ N then
    F.biUnion fun f => (candSuffix b m N T F (i + m)).image (f ++ ·)
  else (Finset.range b).biUnion fun d => (candSuffix b m N T F (i + 1)).image (d :: ·)
termination_by N - i
decreasing_by all_goals omega

theorem ofFn_window_eq (ω : ℕ → ℕ) (m i : ℕ) :
    (List.ofFn fun j : Fin m => ω (i + j)) = (List.range' i m).map ω := by
  induction m generalizing i with
  | zero => simp
  | succ m ih =>
    rw [List.ofFn_succ, List.range'_succ, List.map_cons]
    rw [← ih (i + 1)]
    simp only [Fin.val_zero, add_zero, Fin.val_succ, List.cons.injEq, true_and]
    congr 1; funext j; congr 1; omega

theorem mem_candSuffix (b m N : ℕ) (T : Finset ℕ) (F : Finset (List ℕ)) (ω : ℕ → ℕ)
    (hω : ∀ j, ω j < b) (hgood : ∀ i, i ∉ T → i < N → (List.ofFn fun j : Fin m => ω (i + j)) ∈ F)
    (i : ℕ) : (List.range' i (N - i)).map ω ∈ candSuffix b m N T F i := by
  rw [candSuffix]
  split_ifs with h1 h2
  · simp [show N - i = 0 by omega]
  · have hsplit : List.range' i (N - i) = List.range' i m ++ List.range' (i + m) (N - (i + m)) := by
      have := @List.range'_append i m (N - (i + m)) 1
      simp only [one_mul] at this
      rw [this, show m + (N - (i + m)) = N - i by omega]
    rw [hsplit, List.map_append]
    refine Finset.mem_biUnion.2 ⟨_, ?_, Finset.mem_image.2 ⟨_, mem_candSuffix b m N T F ω hω hgood (i + m), rfl⟩⟩
    rw [← ofFn_window_eq]; exact hgood i h2.1 (by omega)
  · have hsplit : List.range' i (N - i) = i :: List.range' (i + 1) (N - (i + 1)) := by
      rw [show N - i = (N - (i + 1)) + 1 by omega, List.range'_succ]
    rw [hsplit, List.map_cons]
    exact Finset.mem_biUnion.2 ⟨ω i, Finset.mem_range.2 (hω i),
      Finset.mem_image.2 ⟨_, mem_candSuffix b m N T F ω hω hgood (i + 1), rfl⟩⟩
termination_by N - i
decreasing_by all_goals omega

theorem card_candSuffix_le (b m N : ℕ) (hb : 1 ≤ b) (hm : 0 < m) (T : Finset ℕ)
    (F : Finset (List ℕ)) (G : ℝ) (hG : 1 ≤ G) (hF : (F.card : ℝ) ≤ G) (i : ℕ) :
    ((candSuffix b m N T F i).card : ℝ) ≤
      G ^ (((N - i : ℕ) : ℝ) / m) * (b : ℝ) ^ ((T.filter (i ≤ ·)).card + min m (N - i)) := by
  have hb1 : (1 : ℝ) ≤ b := by exact_mod_cast hb
  have hmR : (0 : ℝ) < m := by exact_mod_cast hm
  rw [candSuffix]
  split_ifs with h1 h2
  · simp only [Finset.card_singleton, Nat.cast_one]
    exact one_le_mul_of_one_le_of_one_le (Real.one_le_rpow hG (by positivity)) (one_le_pow₀ hb1)
  · have ih := card_candSuffix_le b m N hb hm T F G hG hF (i + m)
    have hc : ((F.biUnion fun f => (candSuffix b m N T F (i + m)).image (f ++ ·)).card : ℝ) ≤
        F.card * (candSuffix b m N T F (i + m)).card := by
      have := Finset.card_biUnion_le (s := F) (t := fun f => (candSuffix b m N T F (i + m)).image (f ++ ·))
      have h2' : ∑ f ∈ F, ((candSuffix b m N T F (i + m)).image (f ++ ·)).card ≤
          F.card * (candSuffix b m N T F (i + m)).card := by
        calc _ ≤ ∑ f ∈ F, (candSuffix b m N T F (i + m)).card :=
              Finset.sum_le_sum fun f _ => Finset.card_image_le
          _ = _ := by simp
      exact_mod_cast this.trans h2'
    refine hc.trans ?_
    have hT : (T.filter (i + m ≤ ·)).card ≤ (T.filter (i ≤ ·)).card :=
      Finset.card_le_card fun j hj => by
        rw [Finset.mem_filter] at hj ⊢; exact ⟨hj.1, by omega⟩
    have hexp : (((N - i : ℕ) : ℝ) / m) = 1 + ((N - (i + m) : ℕ) : ℝ) / m := by
      rw [Nat.cast_sub (by omega), Nat.cast_sub (by omega)]; field_simp; push_cast; ring
    rw [hexp, Real.rpow_add (by linarith), Real.rpow_one, mul_assoc]
    exact mul_le_mul hF (ih.trans (mul_le_mul_of_nonneg_left
      (pow_le_pow_right₀ hb1 (add_le_add hT (by omega))) (by positivity))) (by positivity)
      (by linarith)
  · have ih := card_candSuffix_le b m N hb hm T F G hG hF (i + 1)
    have hc : (((Finset.range b).biUnion fun d => (candSuffix b m N T F (i + 1)).image (d :: ·)).card : ℝ) ≤
        b * (candSuffix b m N T F (i + 1)).card := by
      have := Finset.card_biUnion_le (s := Finset.range b) (t := fun d => (candSuffix b m N T F (i + 1)).image (d :: ·))
      have h2' : ∑ d ∈ Finset.range b, ((candSuffix b m N T F (i + 1)).image (d :: ·)).card ≤
          b * (candSuffix b m N T F (i + 1)).card := by
        calc _ ≤ ∑ d ∈ Finset.range b, (candSuffix b m N T F (i + 1)).card :=
              Finset.sum_le_sum fun d _ => Finset.card_image_le
          _ = _ := by simp
      exact_mod_cast this.trans h2'
    refine hc.trans ?_
    have hsplitT : (T.filter (i ≤ ·)).card = (T.filter (i + 1 ≤ ·)).card + (if i ∈ T then 1 else 0) := by
      have : T.filter (i ≤ ·) = (T.filter (i + 1 ≤ ·)) ∪ (T.filter (· = i)) := by
        ext j; simp only [Finset.mem_filter, Finset.mem_union]; constructor
        · rintro ⟨h, h'⟩; rcases Nat.lt_or_ge i j with h'' | h''
          · exact Or.inl ⟨h, h''⟩
          · exact Or.inr ⟨h, by omega⟩
        · rintro (⟨h, h'⟩ | ⟨h, h'⟩) <;> exact ⟨h, by omega⟩
      rw [this, Finset.card_union_of_disjoint (Finset.disjoint_filter.2 fun j _ h1 h2 => by omega)]
      congr 1
      split_ifs with h
      · exact Finset.card_eq_one.2 ⟨i, by
          ext j; simp only [Finset.mem_filter, Finset.mem_singleton]
          exact ⟨fun h' => h'.2, fun h' => ⟨h' ▸ h, h'⟩⟩⟩
      · rw [Finset.card_eq_zero, Finset.filter_eq_empty_iff]; intro j hj hji; exact h (hji ▸ hj)
    have hnat : (T.filter (i + 1 ≤ ·)).card + min m (N - (i + 1)) + 1 ≤
        (T.filter (i ≤ ·)).card + min m (N - i) := by
      rw [hsplitT]; split_ifs at h2 ⊢ with h <;> [omega; (push Not at h2; have := h2 h hm; omega)]
    calc (b : ℝ) * (candSuffix b m N T F (i + 1)).card
        ≤ b * (G ^ (((N - (i + 1) : ℕ) : ℝ) / m) *
            (b : ℝ) ^ ((T.filter (i + 1 ≤ ·)).card + min m (N - (i + 1)))) := by gcongr
      _ = G ^ (((N - (i + 1) : ℕ) : ℝ) / m) *
            (b : ℝ) ^ ((T.filter (i + 1 ≤ ·)).card + min m (N - (i + 1)) + 1) := by ring
      _ ≤ _ := mul_le_mul (Real.rpow_le_rpow_of_exponent_le hG
            (div_le_div_of_nonneg_right (Nat.cast_le.2 (by omega)) hmR.le))
            (pow_le_pow_right₀ hb1 hnat) (by positivity) (by positivity)
termination_by N - i
decreasing_by all_goals omega

/-- Subsets of `range N` of size `≤ k`, counted with a weight `r ≤ 1`. -/
theorem card_smallSubsets_le (N k : ℕ) {r : ℝ} (hr0 : 0 < r) (hr1 : r ≤ 1) :
    (((Finset.range N).powerset.filter (fun T => T.card ≤ k)).card : ℝ) ≤ (1 + r) ^ N / r ^ k := by
  rw [le_div_iff₀ (by positivity)]
  have hsum := Finset.sum_pow_mul_eq_add_pow r 1 (Finset.range N)
  simp only [one_pow, mul_one, Finset.card_range] at hsum
  rw [add_comm 1 r, ← hsum, Finset.card_eq_sum_ones, Nat.cast_sum, Finset.sum_mul]
  refine (Finset.sum_le_sum fun T hT => ?_).trans
    (Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _) fun _ _ _ => by positivity)
  simp only [Nat.cast_one, one_mul]
  exact pow_le_pow_of_le_one hr0.le hr1 (Finset.mem_filter.1 hT).2

/-- Base-`b` value of a digit list (most significant first). -/
def digVal (b : ℕ) (w : List ℕ) : ℤ := w.foldl (fun a d => b * a + d) 0

theorem floor_eq_digVal (b : ℕ) (hb : 2 ≤ b) (y : ℝ) (hy0 : 0 ≤ y) (hy1 : y < 1) (N : ℕ) :
    ⌊y * (b : ℝ) ^ N⌋ = digVal b ((List.range' 0 N).map (digitOf b y)) := by
  induction N with
  | zero => simp [digVal, Int.floor_eq_zero_iff.2 ⟨hy0, hy1⟩]
  | succ N ih =>
    have := @List.range'_append 0 N 1 1
    simp only [one_mul, zero_add] at this
    rw [← this, floor_mul_pow_succ b hb y hy0 N, ih]
    simp [digVal, List.foldl_append]

theorem subexp_asymp (b : ℕ) (hb : 2 ≤ b) (ε : ℝ) (hε : 0 < ε) :
    ∃ r ε' : ℝ, 0 < r ∧ r ≤ 1 ∧ 0 < ε' ∧ ε' ≤ 1 / 4 ∧ ∀ m N : ℕ, 2 * (m : ℝ) ≤ ε * N →
      (1 + r) ^ N / r ^ (⌊2 * ε' * N⌋₊) * (2 : ℝ) ^ (ε' * N) * (b : ℝ) ^ (⌊2 * ε' * N⌋₊ + m) ≤
        (b : ℝ) ^ (ε * N) := by
  have hb2 : (2 : ℝ) ≤ b := by exact_mod_cast hb
  have hb0 : (0 : ℝ) < b := by linarith
  set L := Real.log b with hL
  have hL2 : Real.log 2 ≤ L := Real.log_le_log (by norm_num) hb2
  have hL0 : 0 < L := lt_of_lt_of_le (Real.log_pos (by norm_num)) hL2
  set r := min 1 (ε * L / 4) with hr
  have hr0 : 0 < r := lt_min one_pos (by positivity)
  have hr1 : r ≤ 1 := min_le_left _ _
  have hrε : r ≤ ε * L / 4 := min_le_right _ _
  set c := - Real.log r with hc
  have hc0 : 0 ≤ c := by rw [hc, neg_nonneg]; exact Real.log_nonpos hr0.le hr1
  set ε' := min (1 / 4) (ε * L / (4 * (2 * c + 3 * L))) with hε'
  have hden : 0 < 4 * (2 * c + 3 * L) := by positivity
  have hε'0 : 0 < ε' := lt_min (by norm_num) (by positivity)
  have hε'b : ε' * (2 * c + 3 * L) ≤ ε * L / 4 := by
    have : ε' ≤ ε * L / (4 * (2 * c + 3 * L)) := min_le_right _ _
    rw [le_div_iff₀ hden] at this; nlinarith
  refine ⟨r, ε', hr0, hr1, hε'0, min_le_left _ _, fun m N hmN => ?_⟩
  set k := ⌊2 * ε' * N⌋₊
  have hk : (k : ℝ) ≤ 2 * ε' * N := Nat.floor_le (by positivity)
  have hN0 : (0 : ℝ) ≤ N := Nat.cast_nonneg N
  have e1 : (1 + r) ^ N = Real.exp (N * Real.log (1 + r)) := by
    rw [← Real.log_pow, Real.exp_log (by positivity)]
  have e2 : 1 / r ^ k = Real.exp (k * c) := by
    rw [hc, mul_neg, Real.exp_neg, ← Real.log_pow, Real.exp_log (by positivity), one_div]
  have e3 : (2 : ℝ) ^ (ε' * N) = Real.exp (Real.log 2 * (ε' * N)) := Real.rpow_def_of_pos two_pos _
  have e4 : (b : ℝ) ^ (k + m) = Real.exp (((k + m : ℕ) : ℝ) * L) := by
    rw [← Real.log_pow, Real.exp_log (by positivity)]
  have e5 : (b : ℝ) ^ (ε * N) = Real.exp (L * (ε * N)) := Real.rpow_def_of_pos hb0 _
  rw [div_eq_mul_one_div, e1, e2, e3, e4, e5, ← Real.exp_add, ← Real.exp_add, ← Real.exp_add]
  apply Real.exp_le_exp.2
  have hlog1 : Real.log (1 + r) ≤ r := by
    have := Real.log_le_sub_one_of_pos (show 0 < 1 + r by linarith); linarith
  push_cast
  have h1 : (N : ℝ) * Real.log (1 + r) ≤ N * (ε * L / 4) := by
    apply mul_le_mul_of_nonneg_left (hlog1.trans hrε) hN0
  have h2 : (k : ℝ) * c ≤ 2 * ε' * N * c := mul_le_mul_of_nonneg_right hk hc0
  have h3 : Real.log 2 * (ε' * N) ≤ L * (ε' * N) := mul_le_mul_of_nonneg_right hL2 (by positivity)
  have h4 : (k : ℝ) * L ≤ 2 * ε' * N * L := mul_le_mul_of_nonneg_right hk hL0.le
  have h5 : (m : ℝ) * L ≤ ε * N / 2 * L := mul_le_mul_of_nonneg_right (by linarith) hL0.le
  have h6 : N * (ε' * (2 * c + 3 * L)) ≤ N * (ε * L / 4) := mul_le_mul_of_nonneg_left hε'b hN0
  nlinarith

open Classical in
/-- One piece of the cover of `𝒟(b)`: integer part `k`, block length `m`, block family `F`, and a
bad set of density `≤ 2ε'` beyond `N₁`. -/
def detPiece (b : ℕ) (ε' : ℝ) (p : ℤ × ℕ × Finset (List ℕ) × ℕ) : Set ℝ :=
  {x | ⌊x⌋ = p.1 ∧ 0 < p.2.1 ∧ (p.2.2.1.card : ℝ) < (2 : ℝ) ^ (ε' * p.2.1) ∧
    ∃ S : Set ℕ, (∀ N ≥ p.2.2.2, ((((Finset.range N).filter (· ∈ S)).card : ℕ) : ℝ) ≤ 2 * ε' * N) ∧
      ∀ i, i ∉ S → (List.ofFn fun j : Fin p.2.1 => digitOf b (Int.fract x) (i + j)) ∈ p.2.2.1}

open Classical in
theorem subexp_detPiece (b : ℕ) (hb : 2 ≤ b) {ε r ε' : ℝ} (hε : 0 < ε) (hr0 : 0 < r) (hr1 : r ≤ 1)
    (hε'0 : 0 < ε')
    (hasymp : ∀ m N : ℕ, 2 * (m : ℝ) ≤ ε * N →
      (1 + r) ^ N / r ^ (⌊2 * ε' * N⌋₊) * (2 : ℝ) ^ (ε' * N) * (b : ℝ) ^ (⌊2 * ε' * N⌋₊ + m) ≤
        (b : ℝ) ^ (ε * N))
    (p : ℤ × ℕ × Finset (List ℕ) × ℕ) : SubexpCylinderCount b ε (detPiece b ε' p) := by
  obtain ⟨k, m, F, N₁⟩ := p
  have hb0 : (0 : ℝ) < b := Nat.cast_pos.2 (by omega)
  by_cases h : 0 < m ∧ (F.card : ℝ) < (2 : ℝ) ^ (ε' * m)
  swap
  · refine ⟨0, fun N _ => ⟨∅, by simp; positivity, fun x hx => absurd ⟨hx.2.1, hx.2.2.1⟩ h⟩⟩
  obtain ⟨hm, hF⟩ := h
  have hmR : (0 : ℝ) < m := by exact_mod_cast hm
  refine ⟨max N₁ ⌈2 * m / ε⌉₊, fun N hN => ?_⟩
  set K := ⌊2 * ε' * N⌋₊
  set G : ℝ := (2 : ℝ) ^ (ε' * m)
  have hG : 1 ≤ G := Real.one_le_rpow (by norm_num) (by positivity)
  have hGN : G ^ (((N - 0 : ℕ) : ℝ) / m) = (2 : ℝ) ^ (ε' * N) := by
    rw [← Real.rpow_mul (by norm_num)]; congr 1; simp only [Nat.sub_zero]; field_simp
  have hmN : 2 * (m : ℝ) ≤ ε * N := by
    have h1 : (⌈2 * m / ε⌉₊ : ℝ) ≤ N := by exact_mod_cast le_of_max_le_right hN
    have h2 := Nat.le_ceil (2 * (m : ℝ) / ε)
    rw [div_le_iff₀ hε] at h2; nlinarith
  refine ⟨((Finset.range N).powerset.filter (fun Ts => Ts.card ≤ K)).biUnion
    (fun Ts => (candSuffix b m N Ts F 0).image (fun w => k * (b : ℤ) ^ N + digVal b w)), ?_, ?_⟩
  · refine le_trans ?_ (hasymp m N hmN)
    have hcard := Finset.card_biUnion_le (s := (Finset.range N).powerset.filter (fun Ts => Ts.card ≤ K))
      (t := fun Ts => (candSuffix b m N Ts F 0).image (fun w => k * (b : ℤ) ^ N + digVal b w))
    have hterm : ∀ Ts ∈ (Finset.range N).powerset.filter (fun Ts => Ts.card ≤ K),
        ((((candSuffix b m N Ts F 0).image (fun w => k * (b : ℤ) ^ N + digVal b w)).card : ℕ) : ℝ) ≤
          (2 : ℝ) ^ (ε' * N) * (b : ℝ) ^ (K + m) := by
      intro Ts hTs
      have hTsK := (Finset.mem_filter.1 hTs).2
      refine (Nat.cast_le.2 Finset.card_image_le).trans ?_
      refine (card_candSuffix_le b m N (by omega) hm Ts F G hG hF.le 0).trans ?_
      rw [hGN]
      refine mul_le_mul_of_nonneg_left (pow_le_pow_right₀ (by exact_mod_cast (by omega : 1 ≤ b)) ?_)
        (by positivity)
      have : (Ts.filter (0 ≤ ·)).card ≤ Ts.card := Finset.card_filter_le _ _
      have : min m (N - 0) ≤ m := min_le_left _ _
      omega
    calc ((Finset.biUnion _ _).card : ℝ)
        ≤ ∑ Ts ∈ (Finset.range N).powerset.filter (fun Ts => Ts.card ≤ K),
            ((((candSuffix b m N Ts F 0).image (fun w => k * (b : ℤ) ^ N + digVal b w)).card : ℕ) : ℝ) := by
          exact_mod_cast hcard
      _ ≤ ∑ _Ts ∈ (Finset.range N).powerset.filter (fun Ts => Ts.card ≤ K),
            (2 : ℝ) ^ (ε' * N) * (b : ℝ) ^ (K + m) := Finset.sum_le_sum hterm
      _ = (((Finset.range N).powerset.filter (fun Ts => Ts.card ≤ K)).card : ℝ) *
            ((2 : ℝ) ^ (ε' * N) * (b : ℝ) ^ (K + m)) := by rw [Finset.sum_const, nsmul_eq_mul]
      _ ≤ (1 + r) ^ N / r ^ K * ((2 : ℝ) ^ (ε' * N) * (b : ℝ) ^ (K + m)) :=
          mul_le_mul_of_nonneg_right (card_smallSubsets_le N K hr0 hr1) (by positivity)
      _ = _ := by ring
  · rintro x ⟨hk, -, -, S, hS, hwin⟩
    set t := ⌊x * (b : ℝ) ^ N⌋
    have hbN : (0 : ℝ) < (b : ℝ) ^ N := by positivity
    refine mem_iUnion₂.2 ⟨t, ?_, ?_⟩
    · refine Finset.mem_biUnion.2 ⟨(Finset.range N).filter (· ∈ S), ?_, Finset.mem_image.2
        ⟨(List.range' 0 N).map (digitOf b (Int.fract x)), ?_, ?_⟩⟩
      · refine Finset.mem_filter.2 ⟨Finset.mem_powerset.2 (Finset.filter_subset _ _), ?_⟩
        exact Nat.le_floor (hS N (le_of_max_le_left hN))
      · have := mem_candSuffix b m N ((Finset.range N).filter (· ∈ S)) F (digitOf b (Int.fract x))
          (digitOf_lt b hb _) (fun i hi hiN => hwin i fun hiS =>
            hi (Finset.mem_filter.2 ⟨Finset.mem_range.2 hiN, hiS⟩)) 0
        simpa using this
      · rw [← floor_eq_digVal b hb _ (Int.fract_nonneg x) (Int.fract_lt_one x)]
        have hx : x * (b : ℝ) ^ N = ((k * (b : ℤ) ^ N : ℤ) : ℝ) + Int.fract x * (b : ℝ) ^ N := by
          rw [Int.fract, hk]; push_cast; ring
        rw [show t = ⌊x * (b : ℝ) ^ N⌋ from rfl, hx, Int.floor_intCast_add]
    · have h1 := Int.floor_le (x * (b : ℝ) ^ N)
      have h2 := Int.lt_floor_add_one (x * (b : ℝ) ^ N)
      exact ⟨by rw [div_le_iff₀ hbN]; exact h1, by rw [lt_div_iff₀ hbN]; exact h2⟩

/-- **Leaf (a): `𝒟(b)` has packing dimension `0`.**  Confidence 85%.

English proof.  Fix `ε > 0`; pick `ε' > 0` with `H(2ε') + ε' + 2ε' log₂ b < ε log₂ b`
(`H` the binary entropy).  For `x ∈ 𝒟(b)` Def. 3.8 at `ε'` gives `m ≥ 1`, `F` with
`|F| < 2^{ε'm}` and `𝕊` of upper density `≤ ε'`, so `|𝕊 ∩ [0,N)| ≤ 2ε'N` for `N ≥ N₀`.  Index the
pieces by `(k, m, F, N₀) ∈ ℤ × ℕ × Finset (List ℕ) × ℕ` (countable): the set of `x ∈ [k, k+1)`
whose digit windows at positions outside some `𝕊'` with `|𝕊' ∩ [0,N)| ≤ 2ε'N` (all `N ≥ N₀`) lie
in `F`.  A length-`N` prefix of such `x` is fixed by: a phase `φ < m` with at most `2ε'N/m` bad
aligned windows in `φ + mℕ` (pigeonhole), the first `φ` digits (`b^m`), which aligned windows are
bad (`≤ 2^{(N/m) H(2ε')}`), the good windows (`|F|^{N/m} ≤ 2^{ε'N}`), the bad windows
(`b^{2ε'N}`) and the last `< m` digits (`b^m`).  The product is `≤ m b^{2m} 2^{N(H(2ε')+ε')} b^{2ε'N}
≤ b^{εN}` for `N` large.  Each prefix is one `b`-adic interval of rank `N`, shifted by `k`. -/
theorem deterministic_subexp_cover (b : ℕ) (hb : 2 ≤ b) (ε : ℝ) (hε : 0 < ε) :
    ∃ E : ℕ → Set ℝ, (∀ i, SubexpCylinderCount b ε (E i)) ∧
      {x : ℝ | IsDeterministic b x} ⊆ ⋃ i, E i := by
  classical
  obtain ⟨r, ε', hr0, hr1, hε'0, hε'4, hasymp⟩ := subexp_asymp b hb ε hε
  obtain ⟨g, hg⟩ := exists_surjective_nat (ℤ × ℕ × Finset (List ℕ) × ℕ)
  refine ⟨fun n => detPiece b ε' (g n), fun n => subexp_detPiece b hb hε hr0 hr1 hε'0 hasymp _, ?_⟩
  intro x hx
  obtain ⟨m, F, ⟨S, hS, hwin⟩, hF⟩ := hx ε' hε'0
  obtain ⟨N₁, hN₁⟩ := eventually_atTop.1 (hS ε' hε'0)
  have hm : 0 < m := by
    by_contra h0
    have hm0 : m = 0 := by omega
    subst hm0
    have hF0 : F = ∅ := by
      have h1 : F.card < 1 := by exact_mod_cast (by simpa using hF : (F.card : ℝ) < 1)
      exact Finset.card_eq_zero.1 (by omega)
    have hall : ∀ i, i ∈ S := fun i => by_contra fun hi => by simpa [hF0] using hwin i hi
    have := hN₁ (max N₁ 1) (le_max_left _ _)
    have hc : (((Finset.range (max N₁ 1)).filter (· ∈ S)).card) = max N₁ 1 := by
      rw [Finset.filter_true_of_mem fun i _ => hall i, Finset.card_range]
    rw [hc] at this
    have h1 : (1 : ℝ) ≤ (max N₁ 1 : ℕ) := by exact_mod_cast le_max_right _ _
    nlinarith
  obtain ⟨n, hn⟩ := hg (⌊x⌋, m, F, N₁)
  refine mem_iUnion.2 ⟨n, ?_⟩
  rw [hn]
  refine ⟨rfl, hm, hF, S, fun N hN => ?_, hwin⟩
  have := hN₁ N hN
  convert this using 1
  · ring

/-- A product of two rank-`N` `b`-adic cells has sup-metric diameter `≤ b^{-N}`. -/
theorem ediam_cell_prod_le {b : ℕ} (hb : 2 ≤ b) (N : ℕ) (s t : ℤ) :
    Metric.ediam (Ico ((s : ℝ) / (b : ℝ) ^ N) (((s : ℝ) + 1) / (b : ℝ) ^ N) ×ˢ
      Ico ((t : ℝ) / (b : ℝ) ^ N) (((t : ℝ) + 1) / (b : ℝ) ^ N)) ≤
      ENNReal.ofReal (((b : ℝ) ^ N)⁻¹) := by
  have hbN : (0 : ℝ) < (b : ℝ) ^ N := by positivity
  have key : ∀ u : ℤ, ∀ x ∈ Ico ((u : ℝ) / (b : ℝ) ^ N) (((u : ℝ) + 1) / (b : ℝ) ^ N),
      ∀ y ∈ Ico ((u : ℝ) / (b : ℝ) ^ N) (((u : ℝ) + 1) / (b : ℝ) ^ N),
      edist x y ≤ ENNReal.ofReal (((b : ℝ) ^ N)⁻¹) := by
    intro u x hx y hy
    rw [edist_dist, Real.dist_eq]
    apply ENNReal.ofReal_le_ofReal
    have h1 : (((u:ℝ) + 1) / (b:ℝ) ^ N) - (u : ℝ) / (b:ℝ)^N = ((b:ℝ)^N)⁻¹ := by
      field_simp; ring
    rw [abs_le]; constructor <;> linarith [hx.1, hx.2, hy.1, hy.2]
  refine Metric.ediam_le fun p hp q hq => ?_
  rw [Prod.edist_eq]
  exact max_le (key s _ hp.1 _ hq.1) (key t _ hp.2 _ hq.2)

/-- **Leaf (b): box-counting bound for a product.**  Confidence 92%.

English proof.  For `N ≥ max N₀_A N₀_B`, `A ×ˢ B` is covered by `|T_A| |T_B| ≤ b^{2εN}` squares
`[s/b^N, (s+1)/b^N) × [t/b^N, (t+1)/b^N)`, each of sup-metric diameter `b^{-N}`.  For `d > 2ε`,
`μH[d](A ×ˢ B) ≤ liminf_N b^{2εN} b^{-dN} = 0`, so `dimH (A ×ˢ B) ≤ d`.  Only the *every large
scale* count is used; `dimH A = dimH B = 0` alone is not enough (`not_dimH_prod_zero_of_dimH_zero`).
-/
theorem dimH_prod_le_of_subexp {b : ℕ} (hb : 2 ≤ b) {ε : ℝ} (hε : 0 ≤ ε) {A B : Set ℝ}
    (hA : SubexpCylinderCount b ε A) (hB : SubexpCylinderCount b ε B) :
    dimH (A ×ˢ B) ≤ ENNReal.ofReal (2 * ε) := by
  obtain ⟨NA, hA⟩ := hA
  obtain ⟨NB, hB⟩ := hB
  have gA : ∀ N : ℕ, ∃ T : Finset ℤ, NA ≤ N → ((T.card : ℝ) ≤ (b : ℝ) ^ (ε * N) ∧
      A ⊆ ⋃ t ∈ T, Ico ((t : ℝ) / (b : ℝ) ^ N) (((t : ℝ) + 1) / (b : ℝ) ^ N)) := fun N =>
    if h : NA ≤ N then let ⟨T, hT⟩ := hA N h; ⟨T, fun _ => hT⟩ else ⟨∅, fun h' => absurd h' h⟩
  have gB : ∀ N : ℕ, ∃ T : Finset ℤ, NB ≤ N → ((T.card : ℝ) ≤ (b : ℝ) ^ (ε * N) ∧
      B ⊆ ⋃ t ∈ T, Ico ((t : ℝ) / (b : ℝ) ^ N) (((t : ℝ) + 1) / (b : ℝ) ^ N)) := fun N =>
    if h : NB ≤ N then let ⟨T, hT⟩ := hB N h; ⟨T, fun _ => hT⟩ else ⟨∅, fun h' => absurd h' h⟩
  choose TA hTA using gA
  choose TB hTB using gB
  have hb1 : (1 : ℝ) < b := by exact_mod_cast hb
  have hb0 : (0 : ℝ) < b := by linarith
  refine dimH_le fun d hd => ?_
  by_contra hlt
  push Not at hlt
  have hdε : 2 * ε < (d : ℝ) := by
    have := (ENNReal.ofReal_lt_iff_lt_toReal (by positivity) (by simp)).1 hlt
    simpa using this
  let cell : ℕ → ℤ × ℤ → Set (ℝ × ℝ) := fun N p =>
    Ico ((p.1 : ℝ) / (b : ℝ) ^ N) (((p.1 : ℝ) + 1) / (b : ℝ) ^ N) ×ˢ
      Ico ((p.2 : ℝ) / (b : ℝ) ^ N) (((p.2 : ℝ) + 1) / (b : ℝ) ^ N)
  have hle := Measure.hausdorffMeasure_le_liminf_sum (X := ℝ × ℝ) (d : ℝ) (A ×ˢ B) (l := atTop)
    (ι := fun N => (TA N ×ˢ TB N : Finset (ℤ × ℤ))) (fun N : ℕ => ENNReal.ofReal (((b : ℝ) ^ N)⁻¹))
    ?_ (fun N p => cell N p.1) ?_ ?_
  rotate_left
  · rw [← ENNReal.ofReal_zero]
    refine ENNReal.tendsto_ofReal ?_
    exact tendsto_inv_atTop_zero.comp (tendsto_pow_atTop_atTop_of_one_lt hb1)
  · exact Eventually.of_forall fun N p => ediam_cell_prod_le hb N p.1.1 p.1.2
  · filter_upwards [eventually_ge_atTop (max NA NB)] with N hN
    rintro ⟨x, y⟩ ⟨hx, hy⟩
    obtain ⟨-, hAc⟩ := hTA N (le_of_max_le_left hN)
    obtain ⟨-, hBc⟩ := hTB N (le_of_max_le_right hN)
    have hx' := hAc hx
    have hy' := hBc hy
    simp only [mem_iUnion] at hx' hy'
    obtain ⟨s, hs, hxs⟩ := hx'
    obtain ⟨t, ht, hyt⟩ := hy'
    exact mem_iUnion.2 ⟨⟨(s, t), Finset.mem_product.2 ⟨hs, ht⟩⟩, hxs, hyt⟩
  have hzero : μH[d] (A ×ˢ B) = 0 := by
    refine le_antisymm (hle.trans ?_) zero_le
    have hg : Tendsto (fun N : ℕ => ENNReal.ofReal ((b : ℝ) ^ ((2 * ε - d) * N))) atTop (𝓝 0) := by
      rw [← ENNReal.ofReal_zero]
      refine ENNReal.tendsto_ofReal ?_
      have : Tendsto (fun N : ℕ => (2 * ε - d) * (N : ℝ)) atTop atBot :=
        tendsto_natCast_atTop_atTop.const_mul_atTop_of_neg (by linarith) |>.congr fun _ => rfl
      exact (tendsto_rpow_atBot_of_base_gt_one _ hb1).comp this
    refine (liminf_le_liminf ?_).trans (le_of_eq hg.liminf_eq)
    filter_upwards [eventually_ge_atTop (max NA NB)] with N hN
    have hcA := (hTA N (le_of_max_le_left hN)).1
    have hcB := (hTB N (le_of_max_le_right hN)).1
    have hbN : (0 : ℝ) < (b : ℝ) ^ N := by positivity
    calc ∑ p : (TA N ×ˢ TB N : Finset (ℤ × ℤ)), Metric.ediam (cell N p.1) ^ (d : ℝ)
        ≤ ∑ _p : (TA N ×ˢ TB N : Finset (ℤ × ℤ)), ENNReal.ofReal (((b : ℝ) ^ N)⁻¹ ^ (d : ℝ)) := by
          refine Finset.sum_le_sum fun p _ => ?_
          rw [← ENNReal.ofReal_rpow_of_nonneg (x := ((b : ℝ) ^ N)⁻¹) (p := (d : ℝ)) (by positivity) d.2]
          exact ENNReal.rpow_le_rpow (ediam_cell_prod_le hb N p.1.1 p.1.2) d.2
      _ = ENNReal.ofReal (((TA N).card * (TB N).card : ℕ) * ((b : ℝ) ^ N)⁻¹ ^ (d : ℝ)) := by
          rw [Finset.sum_const, Finset.card_univ, Fintype.card_coe, Finset.card_product,
            nsmul_eq_mul, ENNReal.ofReal_mul (by positivity), ENNReal.ofReal_natCast]
      _ ≤ ENNReal.ofReal ((b : ℝ) ^ ((2 * ε - d) * N)) := by
          apply ENNReal.ofReal_le_ofReal
          have e1 : ((b : ℝ) ^ N)⁻¹ ^ (d : ℝ) = (b : ℝ) ^ (-(d : ℝ) * N) := by
            rw [← Real.rpow_natCast, ← Real.rpow_neg_one, ← Real.rpow_mul hb0.le,
              ← Real.rpow_mul hb0.le]; ring_nf
          have e2 : (b : ℝ) ^ ((2 * ε - d) * N) = (b : ℝ) ^ (ε * N) * (b : ℝ) ^ (ε * N) *
              (b : ℝ) ^ (-(d : ℝ) * N) := by
            rw [← Real.rpow_add hb0, ← Real.rpow_add hb0]; ring_nf
          rw [e1, e2]; push_cast
          gcongr
  exact absurd (hd ▸ hzero) (by simp)

/-- A map that is `C¹` at every point of `s` does not raise Hausdorff dimension on `s`. -/
theorem dimH_image_le_of_contDiffAt {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [FiniteDimensional ℝ E] [NormedAddCommGroup F] [NormedSpace ℝ F] {f : E → F} {s : Set E}
    (hf : ∀ x ∈ s, ContDiffAt ℝ 1 f x) : dimH (f '' s) ≤ dimH s :=
  dimH_image_le_of_locally_lipschitzOn fun x hx =>
    let ⟨K, t, ht, hK⟩ := (hf x hx).exists_lipschitzOnWith
    ⟨K, t, mem_nhdsWithin_of_mem_nhds ht, hK⟩

/-- If `dimH s ≤ 2ε` for every `ε > 0` then `dimH s = 0`. -/
theorem dimH_eq_zero_of_forall {X : Type*} [EMetricSpace X] {s : Set X}
    (h : ∀ ε : ℝ, 0 < ε → dimH s ≤ ENNReal.ofReal (2 * ε)) : dimH s = 0 := by
  refine le_antisymm (ENNReal.le_of_forall_pos_le_add fun ε hε _ => ?_) zero_le
  have := h ((ε : ℝ) / 2) (by positivity)
  rw [zero_add]
  convert this using 1
  rw [mul_div_cancel₀ _ (two_ne_zero), ENNReal.ofReal_coe_nnreal]

/-- The set of products of two base-`b` deterministic numbers. -/
def detProducts (b : ℕ) : Set ℝ :=
  {z | ∃ y₁ y₂, IsDeterministic b y₁ ∧ IsDeterministic b y₂ ∧ z = y₁ * y₂}

/-- The set of ratios of two base-`b` deterministic numbers. -/
def detRatios (b : ℕ) : Set ℝ :=
  {z | ∃ y₁ y₂, IsDeterministic b y₁ ∧ IsDeterministic b y₂ ∧ z = y₁ / y₂}

/-- The set of products of reciprocals of two base-`b` deterministic numbers. -/
def detRecipProducts (b : ℕ) : Set ℝ :=
  {z | ∃ y₁ y₂, IsDeterministic b y₁ ∧ IsDeterministic b y₂ ∧ z = y₁⁻¹ * y₂⁻¹}

/-- **(c), products: `dimH (𝒟·𝒟) = 0`.**  From leaves (a), (b). -/
theorem dimH_detProducts (b : ℕ) (hb : 2 ≤ b) : dimH (detProducts b) = 0 := by
  refine dimH_eq_zero_of_forall fun ε hε => ?_
  obtain ⟨E, hE, hcov⟩ := deterministic_subexp_cover b hb ε hε
  have hsub : detProducts b ⊆ ⋃ i, ⋃ j, image2 (· * ·) (E i) (E j) := by
    rintro z ⟨y₁, y₂, h₁, h₂, rfl⟩
    obtain ⟨i, hi⟩ := mem_iUnion.1 (hcov h₁)
    obtain ⟨j, hj⟩ := mem_iUnion.1 (hcov h₂)
    exact mem_iUnion.2 ⟨i, mem_iUnion.2 ⟨j, mem_image2_of_mem hi hj⟩⟩
  refine (dimH_mono hsub).trans ?_
  simp only [dimH_iUnion]
  refine iSup_le fun i => iSup_le fun j => ?_
  rw [← image_uncurry_prod]
  refine (dimH_image_le_of_contDiffAt fun p _ => ?_).trans
    (dimH_prod_le_of_subexp hb hε.le (hE i) (hE j))
  exact (contDiffAt_fst.mul contDiffAt_snd : ContDiffAt ℝ 1 (fun p : ℝ × ℝ => p.1 * p.2) p)

/-- **(c), ratios: `dimH (𝒟/𝒟) = 0`.** -/
theorem dimH_detRatios (b : ℕ) (hb : 2 ≤ b) : dimH (detRatios b) = 0 := by
  refine dimH_eq_zero_of_forall fun ε hε => ?_
  obtain ⟨E, hE, hcov⟩ := deterministic_subexp_cover b hb ε hε
  have hsub : detRatios b ⊆ {0} ∪ ⋃ i, ⋃ j, image2 (· / ·) (E i) (E j \ {0}) := by
    rintro z ⟨y₁, y₂, h₁, h₂, rfl⟩
    by_cases hy : y₂ = 0
    · left; simp [hy]
    right
    obtain ⟨i, hi⟩ := mem_iUnion.1 (hcov h₁)
    obtain ⟨j, hj⟩ := mem_iUnion.1 (hcov h₂)
    exact mem_iUnion.2 ⟨i, mem_iUnion.2 ⟨j, mem_image2_of_mem hi ⟨hj, hy⟩⟩⟩
  refine (dimH_mono hsub).trans ?_
  rw [dimH_union, dimH_singleton]
  simp only [dimH_iUnion]
  refine max_le zero_le (iSup_le fun i => iSup_le fun j => ?_)
  rw [← image_uncurry_prod]
  refine (dimH_image_le_of_contDiffAt fun p hp => ?_).trans
    ((dimH_mono (prod_mono subset_rfl sdiff_subset)).trans
      (dimH_prod_le_of_subexp hb hε.le (hE i) (hE j)))
  have hp2 : p.2 ≠ 0 := hp.2.2
  exact (contDiffAt_fst.div contDiffAt_snd hp2 : ContDiffAt ℝ 1 (fun p : ℝ × ℝ => p.1 / p.2) p)

/-- **(c), reciprocal products: `dimH ((𝒟·𝒟)⁻¹) = 0`.**  `y₁⁻¹ y₂⁻¹ = (y₁ y₂)⁻¹`, and inversion is
`C¹` off `0`. -/
theorem dimH_detRecipProducts (b : ℕ) (hb : 2 ≤ b) : dimH (detRecipProducts b) = 0 := by
  have hsub : detRecipProducts b ⊆ {0} ∪ (fun z : ℝ => z⁻¹) '' (detProducts b \ {0}) := by
    rintro z ⟨y₁, y₂, h₁, h₂, rfl⟩
    by_cases h : y₁ * y₂ = 0
    · left; simp [← mul_inv, h]
    · right; exact ⟨y₁ * y₂, ⟨⟨y₁, y₂, h₁, h₂, rfl⟩, h⟩, by show (y₁ * y₂)⁻¹ = _; exact mul_inv y₁ y₂⟩
  refine le_antisymm ((dimH_mono hsub).trans ?_) zero_le
  rw [dimH_union, dimH_singleton]
  refine max_le zero_le ?_
  refine (dimH_image_le_of_contDiffAt fun z hz => contDiffAt_inv ℝ hz.2).trans ?_
  exact (dimH_mono sdiff_subset).trans (dimH_detProducts b hb).le

/-- `dimH s = 0` makes `s` Lebesgue-null. -/
theorem volume_eq_zero_of_dimH_eq_zero {s : Set ℝ} (h : dimH s = 0) : volume s = 0 := by
  have := hausdorffMeasure_of_dimH_lt (s := s) (d := 1) (by rw [h]; norm_num)
  rwa [NNReal.coe_one, hausdorffMeasure_real] at this

/-- `dimH s = 0` leaves a positive real outside `s`. -/
theorem exists_pos_not_mem_of_dimH_eq_zero {s : Set ℝ} (h : dimH s = 0) : ∃ z : ℝ, 0 < z ∧ z ∉ s := by
  have hd : Dense sᶜ := dense_compl_of_dimH_lt_finrank (by rw [h]; simp)
  obtain ⟨z, hz, hzs⟩ := hd.inter_open_nonempty (Ioi 0) isOpen_Ioi ⟨1, by norm_num⟩
  exact ⟨z, hz, hzs⟩

/-- **B-D question 4(i): No** (Lebesgue form). -/
theorem volume_detProducts (b : ℕ) (hb : 2 ≤ b) : volume (detProducts b) = 0 :=
  volume_eq_zero_of_dimH_eq_zero (dimH_detProducts b hb)

/-- **B-D question 4(ii): No** (Lebesgue form). -/
theorem volume_detRatios (b : ℕ) (hb : 2 ≤ b) : volume (detRatios b) = 0 :=
  volume_eq_zero_of_dimH_eq_zero (dimH_detRatios b hb)

/-- **B-D question 4(iii): No** (Lebesgue form). -/
theorem volume_detRecipProducts (b : ℕ) (hb : 2 ≤ b) : volume (detRecipProducts b) = 0 :=
  volume_eq_zero_of_dimH_eq_zero (dimH_detRecipProducts b hb)

/-- **Answer to B-D question 4(i): No.** -/
theorem not_productQuestion (b : ℕ) (hb : 2 ≤ b) : ¬ ProductQuestion b := by
  intro h
  obtain ⟨z, hz, hzs⟩ := exists_pos_not_mem_of_dimH_eq_zero (dimH_detProducts b hb)
  exact hzs (h z hz.ne')

/-- **Answer to B-D question 4(ii): No.** -/
theorem not_ratioQuestion (b : ℕ) (hb : 2 ≤ b) : ¬ RatioQuestion b := by
  intro h
  obtain ⟨z, hz, hzs⟩ := exists_pos_not_mem_of_dimH_eq_zero (dimH_detRatios b hb)
  exact hzs (h z hz.ne')

/-- **Answer to B-D question 4(iii): No.** -/
theorem not_recipProductQuestion (b : ℕ) (hb : 2 ≤ b) : ¬ RecipProductQuestion b := by
  intro h
  obtain ⟨z, hz, hzs⟩ := exists_pos_not_mem_of_dimH_eq_zero (dimH_detRecipProducts b hb)
  exact hzs (h z hz.ne')

/-! ## Known-false sibling: Hausdorff dimension `0` alone does not suffice -/

/-- **Control for leaf (b).**  Given that Liouville numbers have `dimH 0` and multiply onto
`ℝ \ {0}` (Erdős 1962), the weakening of `dimH_prod_le_of_subexp` to hypotheses `dimH A = 0`,
`dimH B = 0` is false.  So the proof of item 4 must use the every-scale cylinder count of
`SubexpCylinderCount` (packing dimension `0`); the Liouville set is a dense `G_δ` of packing
dimension `1`. -/
theorem not_dimH_prod_zero_of_dimH_zero (hL : Literature.Liouville.DimHZero)
    (hE : Literature.Liouville.Erdos1962Product) :
    ¬ ∀ A B : Set ℝ, dimH A = 0 → dimH B = 0 → dimH (A ×ˢ B) = 0 := by
  intro h
  set L := {x : ℝ | _root_.Liouville x}
  have hprod := h L L hL hL
  have himg : dimH (image2 (· * ·) L L) = 0 := by
    refine le_antisymm ?_ zero_le
    rw [← image_uncurry_prod, ← hprod]
    exact dimH_image_le_of_contDiffAt fun p _ =>
      (contDiffAt_fst.mul contDiffAt_snd : ContDiffAt ℝ 1 (fun p : ℝ × ℝ => p.1 * p.2) p)
  obtain ⟨z, hz, hzs⟩ := exists_pos_not_mem_of_dimH_eq_zero himg
  obtain ⟨x, y, hx, hy, rfl⟩ := hE z hz.ne'
  exact hzs (mem_image2_of_mem hx hy)

end NormalNumbers.Deterministic
