import NormalNumbers.Headline
import NormalNumbers.CFScheduleA
#print axioms exists_absolutely_normal_cf_normal
#print axioms exists_absolutely_normal_cf_normal_khinchin
#print axioms exists_cfNormal_and_affine_cfNormal
